/**
 * CDISC Library API
 *
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CdashigDomainRefElement } from './cdashigDomainRefElement';
import { CdashigClassDomainsRef } from './cdashigClassDomainsRef';


export interface CdashigClassDomainsLinks { 
    self?: CdashigClassDomainsRef;
    domains?: Array<CdashigDomainRefElement>;
}

