/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAICdashigProductLinks.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAICdashigProductLinks::OAICdashigProductLinks(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAICdashigProductLinks::OAICdashigProductLinks() {
    this->initializeModel();
}

OAICdashigProductLinks::~OAICdashigProductLinks() {}

void OAICdashigProductLinks::initializeModel() {

    m_self_isSet = false;
    m_self_isValid = false;

    m_model_isSet = false;
    m_model_isValid = false;

    m_prior_version_isSet = false;
    m_prior_version_isValid = false;
}

void OAICdashigProductLinks::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAICdashigProductLinks::fromJsonObject(QJsonObject json) {

    m_self_isValid = ::OpenAPI::fromJsonValue(m_self, json[QString("self")]);
    m_self_isSet = !json[QString("self")].isNull() && m_self_isValid;

    m_model_isValid = ::OpenAPI::fromJsonValue(m_model, json[QString("model")]);
    m_model_isSet = !json[QString("model")].isNull() && m_model_isValid;

    m_prior_version_isValid = ::OpenAPI::fromJsonValue(m_prior_version, json[QString("priorVersion")]);
    m_prior_version_isSet = !json[QString("priorVersion")].isNull() && m_prior_version_isValid;
}

QString OAICdashigProductLinks::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAICdashigProductLinks::asJsonObject() const {
    QJsonObject obj;
    if (m_self.isSet()) {
        obj.insert(QString("self"), ::OpenAPI::toJsonValue(m_self));
    }
    if (m_model.isSet()) {
        obj.insert(QString("model"), ::OpenAPI::toJsonValue(m_model));
    }
    if (m_prior_version.isSet()) {
        obj.insert(QString("priorVersion"), ::OpenAPI::toJsonValue(m_prior_version));
    }
    return obj;
}

OAICdashigProductRef OAICdashigProductLinks::getSelf() const {
    return m_self;
}
void OAICdashigProductLinks::setSelf(const OAICdashigProductRef &self) {
    m_self = self;
    m_self_isSet = true;
}

bool OAICdashigProductLinks::is_self_Set() const{
    return m_self_isSet;
}

bool OAICdashigProductLinks::is_self_Valid() const{
    return m_self_isValid;
}

OAICdashProductRef OAICdashigProductLinks::getModel() const {
    return m_model;
}
void OAICdashigProductLinks::setModel(const OAICdashProductRef &model) {
    m_model = model;
    m_model_isSet = true;
}

bool OAICdashigProductLinks::is_model_Set() const{
    return m_model_isSet;
}

bool OAICdashigProductLinks::is_model_Valid() const{
    return m_model_isValid;
}

OAICdashigProductRef OAICdashigProductLinks::getPriorVersion() const {
    return m_prior_version;
}
void OAICdashigProductLinks::setPriorVersion(const OAICdashigProductRef &prior_version) {
    m_prior_version = prior_version;
    m_prior_version_isSet = true;
}

bool OAICdashigProductLinks::is_prior_version_Set() const{
    return m_prior_version_isSet;
}

bool OAICdashigProductLinks::is_prior_version_Valid() const{
    return m_prior_version_isValid;
}

bool OAICdashigProductLinks::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_self.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_model.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_prior_version.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAICdashigProductLinks::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
