/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIExportCdashigTable.h
 *
 * 
 */

#ifndef OAIExportCdashigTable_H
#define OAIExportCdashigTable_H

#include <QJsonObject>

#include "OAIExportCdashigDomainVariablesRow.h"
#include "OAIExportCdashigScenarioVariablesRow.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIExportCdashigDomainVariablesRow;
class OAIExportCdashigScenarioVariablesRow;

class OAIExportCdashigTable : public OAIObject {
public:
    OAIExportCdashigTable();
    OAIExportCdashigTable(QString json);
    ~OAIExportCdashigTable() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAIExportCdashigDomainVariablesRow> getDomainVariables() const;
    void setDomainVariables(const QList<OAIExportCdashigDomainVariablesRow> &domain_variables);
    bool is_domain_variables_Set() const;
    bool is_domain_variables_Valid() const;

    QList<OAIExportCdashigScenarioVariablesRow> getScenarioVariables() const;
    void setScenarioVariables(const QList<OAIExportCdashigScenarioVariablesRow> &scenario_variables);
    bool is_scenario_variables_Set() const;
    bool is_scenario_variables_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<OAIExportCdashigDomainVariablesRow> m_domain_variables;
    bool m_domain_variables_isSet;
    bool m_domain_variables_isValid;

    QList<OAIExportCdashigScenarioVariablesRow> m_scenario_variables;
    bool m_scenario_variables_isSet;
    bool m_scenario_variables_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIExportCdashigTable)

#endif // OAIExportCdashigTable_H
