/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIQrsItemLinks.h
 *
 * 
 */

#ifndef OAIQrsItemLinks_H
#define OAIQrsItemLinks_H

#include <QJsonObject>

#include "OAIQrsResponsegroup.h"
#include "OAIRootCtTermRef.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIRootCtTermRef;
class OAIQrsResponsegroup;

class OAIQrsItemLinks : public OAIObject {
public:
    OAIQrsItemLinks();
    OAIQrsItemLinks(QString json);
    ~OAIQrsItemLinks() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIRootCtTermRef getQrsItemTest() const;
    void setQrsItemTest(const OAIRootCtTermRef &qrs_item_test);
    bool is_qrs_item_test_Set() const;
    bool is_qrs_item_test_Valid() const;

    OAIRootCtTermRef getQrsItemTestcd() const;
    void setQrsItemTestcd(const OAIRootCtTermRef &qrs_item_testcd);
    bool is_qrs_item_testcd_Set() const;
    bool is_qrs_item_testcd_Valid() const;

    OAIRootCtTermRef getQrsItemEval() const;
    void setQrsItemEval(const OAIRootCtTermRef &qrs_item_eval);
    bool is_qrs_item_eval_Set() const;
    bool is_qrs_item_eval_Valid() const;

    OAIRootCtTermRef getQrsItemScat() const;
    void setQrsItemScat(const OAIRootCtTermRef &qrs_item_scat);
    bool is_qrs_item_scat_Set() const;
    bool is_qrs_item_scat_Valid() const;

    OAIQrsResponsegroup getResponsegroup() const;
    void setResponsegroup(const OAIQrsResponsegroup &responsegroup);
    bool is_responsegroup_Set() const;
    bool is_responsegroup_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIRootCtTermRef m_qrs_item_test;
    bool m_qrs_item_test_isSet;
    bool m_qrs_item_test_isValid;

    OAIRootCtTermRef m_qrs_item_testcd;
    bool m_qrs_item_testcd_isSet;
    bool m_qrs_item_testcd_isValid;

    OAIRootCtTermRef m_qrs_item_eval;
    bool m_qrs_item_eval_isSet;
    bool m_qrs_item_eval_isValid;

    OAIRootCtTermRef m_qrs_item_scat;
    bool m_qrs_item_scat_isSet;
    bool m_qrs_item_scat_isValid;

    OAIQrsResponsegroup m_responsegroup;
    bool m_responsegroup_isSet;
    bool m_responsegroup_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIQrsItemLinks)

#endif // OAIQrsItemLinks_H
