/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIXmlCdashigDomainFields.h
 *
 * 
 */

#ifndef OAIXmlCdashigDomainFields_H
#define OAIXmlCdashigDomainFields_H

#include <QJsonObject>

#include "OAICdashigDomainFields.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAICdashigDomainFields;

class OAIXmlCdashigDomainFields : public OAIObject {
public:
    OAIXmlCdashigDomainFields();
    OAIXmlCdashigDomainFields(QString json);
    ~OAIXmlCdashigDomainFields() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAICdashigDomainFields getSelf() const;
    void setSelf(const OAICdashigDomainFields &self);
    bool is_self_Set() const;
    bool is_self_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAICdashigDomainFields m_self;
    bool m_self_isSet;
    bool m_self_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIXmlCdashigDomainFields)

#endif // OAIXmlCdashigDomainFields_H
