/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIXmlCdashigProductScenarios.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIXmlCdashigProductScenarios::OAIXmlCdashigProductScenarios(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIXmlCdashigProductScenarios::OAIXmlCdashigProductScenarios() {
    this->initializeModel();
}

OAIXmlCdashigProductScenarios::~OAIXmlCdashigProductScenarios() {}

void OAIXmlCdashigProductScenarios::initializeModel() {

    m_self_isSet = false;
    m_self_isValid = false;
}

void OAIXmlCdashigProductScenarios::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIXmlCdashigProductScenarios::fromJsonObject(QJsonObject json) {

    m_self_isValid = ::OpenAPI::fromJsonValue(m_self, json[QString("self")]);
    m_self_isSet = !json[QString("self")].isNull() && m_self_isValid;
}

QString OAIXmlCdashigProductScenarios::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIXmlCdashigProductScenarios::asJsonObject() const {
    QJsonObject obj;
    if (m_self.isSet()) {
        obj.insert(QString("self"), ::OpenAPI::toJsonValue(m_self));
    }
    return obj;
}

OAICdashigProductScenarios OAIXmlCdashigProductScenarios::getSelf() const {
    return m_self;
}
void OAIXmlCdashigProductScenarios::setSelf(const OAICdashigProductScenarios &self) {
    m_self = self;
    m_self_isSet = true;
}

bool OAIXmlCdashigProductScenarios::is_self_Set() const{
    return m_self_isSet;
}

bool OAIXmlCdashigProductScenarios::is_self_Valid() const{
    return m_self_isValid;
}

bool OAIXmlCdashigProductScenarios::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_self.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIXmlCdashigProductScenarios::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
