# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SDTMImplementationGuideSDTMIGApi")

api_instance <- SDTMImplementationGuideSDTMIGApi$new()

test_that("MdrRootSdtmigDatasetsDatasetVariablesVarGet", {
  # tests for MdrRootSdtmigDatasetsDatasetVariablesVarGet
  # base path: https://library.cdisc.org/api
  # Get Root SDTMIG Dataset Variable
  # @param dataset character SDTMIG Dataset Identifier
  # @param var character SDTMIG Variable Identifier
  # @return [RootSdtmigDatasetVariable]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MdrSdtmigVersionClassesClassDatasetsGet", {
  # tests for MdrSdtmigVersionClassesClassDatasetsGet
  # base path: https://library.cdisc.org/api
  # Get SDTMIG Class Dataset List
  # @param version character CDISC Library Product Version
  # @param class character SDTMIG Class Identifier
  # @return [SdtmigClassDatasets]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MdrSdtmigVersionClassesClassGet", {
  # tests for MdrSdtmigVersionClassesClassGet
  # base path: https://library.cdisc.org/api
  # Get SDTMIG Class
  # @param version character CDISC Library Product Version
  # @param class character SDTMIG Class Identifier
  # @return [SdtmigClass]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MdrSdtmigVersionClassesGet", {
  # tests for MdrSdtmigVersionClassesGet
  # base path: https://library.cdisc.org/api
  # Get SDTMIG Class List
  # @param version character CDISC Library Product Version
  # @return [SdtmigClasses]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MdrSdtmigVersionDatasetsDatasetGet", {
  # tests for MdrSdtmigVersionDatasetsDatasetGet
  # base path: https://library.cdisc.org/api
  # Get SDTMIG Dataset
  # @param version character CDISC Library Product Version
  # @param dataset character SDTMIG Dataset Identifier
  # @return [SdtmigDataset]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MdrSdtmigVersionDatasetsDatasetVariablesGet", {
  # tests for MdrSdtmigVersionDatasetsDatasetVariablesGet
  # base path: https://library.cdisc.org/api
  # Get SDTMIG Dataset Variable List
  # @param version character CDISC Library Product Version
  # @param dataset character SDTMIG Dataset Identifier
  # @return [SdtmigDatasetVariables]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MdrSdtmigVersionDatasetsDatasetVariablesVarGet", {
  # tests for MdrSdtmigVersionDatasetsDatasetVariablesVarGet
  # base path: https://library.cdisc.org/api
  # Get SDTMIG Dataset Variable
  # @param version character CDISC Library Product Version
  # @param dataset character SDTMIG Dataset Identifier
  # @param var character SDTMIG Variable Identifier
  # @return [SdtmigDatasetVariable]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MdrSdtmigVersionDatasetsGet", {
  # tests for MdrSdtmigVersionDatasetsGet
  # base path: https://library.cdisc.org/api
  # Get SDTMIG Dataset List
  # @param version character CDISC Library Product Version
  # @return [SdtmigDatasets]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MdrSdtmigVersionGet", {
  # tests for MdrSdtmigVersionGet
  # base path: https://library.cdisc.org/api
  # Get SDTMIG product
  # @param version character CDISC Library Product Version
  # @return [SdtmigProduct]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
