/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CtPackageCodelists } from './ctPackageCodelists';
import { CtPackageLinks } from './ctPackageLinks';

export class CtPackage {
    'name'?: string;
    'label'?: string;
    'description'?: string;
    'source'?: string;
    'effectiveDate'?: string;
    'registrationStatus'?: string;
    'version'?: string;
    'links'?: CtPackageLinks;
    'codelists'?: Array<CtPackageCodelists>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        },
        {
            "name": "effectiveDate",
            "baseName": "effectiveDate",
            "type": "string"
        },
        {
            "name": "registrationStatus",
            "baseName": "registrationStatus",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "links",
            "baseName": "_links",
            "type": "CtPackageLinks"
        },
        {
            "name": "codelists",
            "baseName": "codelists",
            "type": "Array<CtPackageCodelists>"
        }    ];

    static getAttributeTypeMap() {
        return CtPackage.attributeTypeMap;
    }
}

