# NOTE: This file is auto generated by OpenAPI Generator 7.16.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CDISCLibraryAPI.Model.CdashigClassScenariosLinks do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :self,
    :scenarios
  ]

  @type t :: %__MODULE__{
    :self => CDISCLibraryAPI.Model.CdashigClassScenariosRef.t | nil,
    :scenarios => [CDISCLibraryAPI.Model.CdashigScenarioRefElement.t] | nil
  }

  alias CDISCLibraryAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:self, :struct, CDISCLibraryAPI.Model.CdashigClassScenariosRef)
     |> Deserializer.deserialize(:scenarios, :list, CDISCLibraryAPI.Model.CdashigScenarioRefElement)
  end
end

