# NOTE: This file is auto generated by OpenAPI Generator 7.16.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CDISCLibraryAPI.Model.ExportAdamVariablesRow do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :Version,
    :"Data Structure Name",
    :"Dataset Name",
    :"Variable Group",
    :"Variable Name",
    :"Variable Label",
    :Type,
    :"Codelist/Controlled Terms",
    :Core,
    :"CDISC Notes"
  ]

  @type t :: %__MODULE__{
    :Version => String.t | nil,
    :"Data Structure Name" => String.t | nil,
    :"Dataset Name" => String.t | nil,
    :"Variable Group" => String.t | nil,
    :"Variable Name" => String.t | nil,
    :"Variable Label" => String.t | nil,
    :Type => String.t | nil,
    :"Codelist/Controlled Terms" => String.t | nil,
    :Core => String.t | nil,
    :"CDISC Notes" => String.t | nil
  }

  def decode(value) do
    value
  end
end

