# NOTE: This file is auto generated by OpenAPI Generator 7.16.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CDISCLibraryAPI.Model.RootSdtmClassVariableLinks do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :self,
    :versions
  ]

  @type t :: %__MODULE__{
    :self => CDISCLibraryAPI.Model.RootSdtmClassVariableRef.t | nil,
    :versions => [CDISCLibraryAPI.Model.SdtmClassVariableRefVersion.t] | nil
  }

  alias CDISCLibraryAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:self, :struct, CDISCLibraryAPI.Model.RootSdtmClassVariableRef)
     |> Deserializer.deserialize(:versions, :list, CDISCLibraryAPI.Model.SdtmClassVariableRefVersion)
  end
end

