# NOTE: This file is auto generated by OpenAPI Generator 7.16.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CDISCLibraryAPI.Model.SdtmClassesLinks do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :self,
    :priorVersion,
    :classes
  ]

  @type t :: %__MODULE__{
    :self => CDISCLibraryAPI.Model.SdtmClassesRef.t | nil,
    :priorVersion => CDISCLibraryAPI.Model.SdtmClassesRef.t | nil,
    :classes => [CDISCLibraryAPI.Model.SdtmClassRefElement.t] | nil
  }

  alias CDISCLibraryAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:self, :struct, CDISCLibraryAPI.Model.SdtmClassesRef)
     |> Deserializer.deserialize(:priorVersion, :struct, CDISCLibraryAPI.Model.SdtmClassesRef)
     |> Deserializer.deserialize(:classes, :list, CDISCLibraryAPI.Model.SdtmClassRefElement)
  end
end

