/*
 * _mdr_search_scopes_get_200_response.h
 *
 * 
 */

#ifndef __mdr_search_scopes_get_200_response_H_
#define __mdr_search_scopes_get_200_response_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct _mdr_search_scopes_get_200_response_t _mdr_search_scopes_get_200_response_t;

#include "default_search_scopes.h"

// Enum  for _mdr_search_scopes_get_200_response

typedef enum  { cdisc_library_api__mdr_search_scopes_get_200_response__NULL = 0, cdisc_library_api__mdr_search_scopes_get_200_response___class, cdisc_library_api__mdr_search_scopes_get_200_response__codelist, cdisc_library_api__mdr_search_scopes_get_200_response__conceptId, cdisc_library_api__mdr_search_scopes_get_200_response__core, cdisc_library_api__mdr_search_scopes_get_200_response__dataStructure, cdisc_library_api__mdr_search_scopes_get_200_response__datasetStructure, cdisc_library_api__mdr_search_scopes_get_200_response__definition, cdisc_library_api__mdr_search_scopes_get_200_response__description, cdisc_library_api__mdr_search_scopes_get_200_response__domain, cdisc_library_api__mdr_search_scopes_get_200_response__effectiveDate, cdisc_library_api__mdr_search_scopes_get_200_response__extensible, cdisc_library_api__mdr_search_scopes_get_200_response__href, cdisc_library_api__mdr_search_scopes_get_200_response__label, cdisc_library_api__mdr_search_scopes_get_200_response__measureType, cdisc_library_api__mdr_search_scopes_get_200_response__name, cdisc_library_api__mdr_search_scopes_get_200_response__preferredTerm, cdisc_library_api__mdr_search_scopes_get_200_response__product, cdisc_library_api__mdr_search_scopes_get_200_response__productGroup, cdisc_library_api__mdr_search_scopes_get_200_response__registrationStatus, cdisc_library_api__mdr_search_scopes_get_200_response__roleDescription, cdisc_library_api__mdr_search_scopes_get_200_response__sdtmTarget, cdisc_library_api__mdr_search_scopes_get_200_response__simpleDatatype, cdisc_library_api__mdr_search_scopes_get_200_response__submissionValue, cdisc_library_api__mdr_search_scopes_get_200_response__synonyms, cdisc_library_api__mdr_search_scopes_get_200_response__type, cdisc_library_api__mdr_search_scopes_get_200_response__uiHref, cdisc_library_api__mdr_search_scopes_get_200_response__valueDomain, cdisc_library_api__mdr_search_scopes_get_200_response__variableSet, cdisc_library_api__mdr_search_scopes_get_200_response__version } cdisc_library_api__mdr_search_scopes_get_200_response__e;

char* _mdr_search_scopes_get_200_response_scopes_ToString(cdisc_library_api__mdr_search_scopes_get_200_response__e scopes);

cdisc_library_api__mdr_search_scopes_get_200_response__e _mdr_search_scopes_get_200_response_scopes_FromString(char* scopes);



typedef struct _mdr_search_scopes_get_200_response_t {
    list_t *scopes; //nonprimitive container

    int _library_owned; // Is the library responsible for freeing this object?
} _mdr_search_scopes_get_200_response_t;

__attribute__((deprecated)) _mdr_search_scopes_get_200_response_t *_mdr_search_scopes_get_200_response_create(
    list_t *scopes
);

void _mdr_search_scopes_get_200_response_free(_mdr_search_scopes_get_200_response_t *_mdr_search_scopes_get_200_response);

_mdr_search_scopes_get_200_response_t *_mdr_search_scopes_get_200_response_parseFromJSON(cJSON *_mdr_search_scopes_get_200_responseJSON);

cJSON *_mdr_search_scopes_get_200_response_convertToJSON(_mdr_search_scopes_get_200_response_t *_mdr_search_scopes_get_200_response);

#endif /* __mdr_search_scopes_get_200_response_H_ */

