/**
 * CDISC Library API
 *
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CdashProductRef } from './cdashProductRef';
import { CdashDomainRefElement } from './cdashDomainRefElement';
import { CdashProductDomainsRef } from './cdashProductDomainsRef';


export interface CdashProductDomainsLinks { 
    self?: CdashProductDomainsRef;
    parentProduct?: CdashProductRef;
    domains?: Array<CdashDomainRefElement>;
}

