/**
 * CDISC Library API
 *
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExportSdtmDatasetVariablesRow } from './exportSdtmDatasetVariablesRow';
import { ExportSdtmClassVariablesRow } from './exportSdtmClassVariablesRow';
import { ExportSdtmDatasetsRow } from './exportSdtmDatasetsRow';


export interface ExportSdtmWorkbook { 
    'class-variables'?: Array<ExportSdtmClassVariablesRow>;
    'dataset-variables'?: Array<ExportSdtmDatasetVariablesRow>;
    datasets?: Array<ExportSdtmDatasetsRow>;
}

