/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SdtmigDatasetRefElement } from './sdtmigDatasetRefElement';
import { SdtmigDatasetsRef } from './sdtmigDatasetsRef';
import { SdtmigProductRef } from './sdtmigProductRef';

export class SdtmigDatasetsLinks {
    'self'?: SdtmigDatasetsRef;
    'parentProduct'?: SdtmigProductRef;
    'priorVersion'?: SdtmigDatasetsRef;
    'datasets'?: Array<SdtmigDatasetRefElement>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "self",
            "baseName": "self",
            "type": "SdtmigDatasetsRef"
        },
        {
            "name": "parentProduct",
            "baseName": "parentProduct",
            "type": "SdtmigProductRef"
        },
        {
            "name": "priorVersion",
            "baseName": "priorVersion",
            "type": "SdtmigDatasetsRef"
        },
        {
            "name": "datasets",
            "baseName": "datasets",
            "type": "Array<SdtmigDatasetRefElement>"
        }    ];

    static getAttributeTypeMap() {
        return SdtmigDatasetsLinks.attributeTypeMap;
    }
}

