/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.16.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QrsResponsegroup.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_QrsResponsegroup_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_QrsResponsegroup_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/QrsResponsegroupLinks.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class QrsResponsegroupLinks;


class  QrsResponsegroup
    : public ModelBase
{
public:
    QrsResponsegroup();
    virtual ~QrsResponsegroup();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// QrsResponsegroup members


    utility::string_t getLabel() const;
    bool labelIsSet() const;
    void unsetLabel();
    void setLabel(const utility::string_t& value);

    std::shared_ptr<QrsResponsegroupLinks> getLinks() const;
    bool linksIsSet() const;
    void unset_links();
    void setLinks(const std::shared_ptr<QrsResponsegroupLinks>& value);


protected:
    utility::string_t m_Label;
    bool m_LabelIsSet;

    std::shared_ptr<QrsResponsegroupLinks> m__links;
    bool m__linksIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_QrsResponsegroup_H_ */
