/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.16.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendigDatasetVariableLinks.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SendigDatasetVariableLinks_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SendigDatasetVariableLinks_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/RootCtCodelistRefElement.h"
#include "CppRestOpenAPIClient/model/SendigDatasetRef.h"
#include "CppRestOpenAPIClient/model/SendigProductRef.h"
#include "CppRestOpenAPIClient/model/RootSendigDatasetVariableRef.h"
#include "CppRestOpenAPIClient/model/SendigDatasetVariableRef.h"
#include "CppRestOpenAPIClient/model/SdtmClassVariableRef.h"
#include "CppRestOpenAPIClient/model/SdtmDatasetVariableRef.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class SendigDatasetVariableRef;
class RootCtCodelistRefElement;
class SdtmClassVariableRef;
class SdtmDatasetVariableRef;
class SendigProductRef;
class SendigDatasetRef;
class RootSendigDatasetVariableRef;


class  SendigDatasetVariableLinks
    : public ModelBase
{
public:
    SendigDatasetVariableLinks();
    virtual ~SendigDatasetVariableLinks();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SendigDatasetVariableLinks members


    std::shared_ptr<SendigDatasetVariableRef> getSelf() const;
    bool selfIsSet() const;
    void unsetSelf();
    void setSelf(const std::shared_ptr<SendigDatasetVariableRef>& value);

    std::vector<std::shared_ptr<RootCtCodelistRefElement>> getCodelist() const;
    bool codelistIsSet() const;
    void unsetCodelist();
    void setCodelist(const std::vector<std::shared_ptr<RootCtCodelistRefElement>>& value);

    std::shared_ptr<SdtmClassVariableRef> getModelClassVariable() const;
    bool modelClassVariableIsSet() const;
    void unsetModelClassVariable();
    void setModelClassVariable(const std::shared_ptr<SdtmClassVariableRef>& value);

    std::shared_ptr<SdtmDatasetVariableRef> getModelDatasetVariable() const;
    bool modelDatasetVariableIsSet() const;
    void unsetModelDatasetVariable();
    void setModelDatasetVariable(const std::shared_ptr<SdtmDatasetVariableRef>& value);

    std::shared_ptr<SendigProductRef> getParentProduct() const;
    bool parentProductIsSet() const;
    void unsetParentProduct();
    void setParentProduct(const std::shared_ptr<SendigProductRef>& value);

    std::shared_ptr<SendigDatasetRef> getParentDataset() const;
    bool parentDatasetIsSet() const;
    void unsetParentDataset();
    void setParentDataset(const std::shared_ptr<SendigDatasetRef>& value);

    std::shared_ptr<RootSendigDatasetVariableRef> getRootItem() const;
    bool rootItemIsSet() const;
    void unsetRootItem();
    void setRootItem(const std::shared_ptr<RootSendigDatasetVariableRef>& value);

    std::shared_ptr<SendigDatasetVariableRef> getPriorVersion() const;
    bool priorVersionIsSet() const;
    void unsetPriorVersion();
    void setPriorVersion(const std::shared_ptr<SendigDatasetVariableRef>& value);


protected:
    std::shared_ptr<SendigDatasetVariableRef> m_Self;
    bool m_SelfIsSet;

    std::vector<std::shared_ptr<RootCtCodelistRefElement>> m_Codelist;
    bool m_CodelistIsSet;

    std::shared_ptr<SdtmClassVariableRef> m_ModelClassVariable;
    bool m_ModelClassVariableIsSet;

    std::shared_ptr<SdtmDatasetVariableRef> m_ModelDatasetVariable;
    bool m_ModelDatasetVariableIsSet;

    std::shared_ptr<SendigProductRef> m_ParentProduct;
    bool m_ParentProductIsSet;

    std::shared_ptr<SendigDatasetRef> m_ParentDataset;
    bool m_ParentDatasetIsSet;

    std::shared_ptr<RootSendigDatasetVariableRef> m_RootItem;
    bool m_RootItemIsSet;

    std::shared_ptr<SendigDatasetVariableRef> m_PriorVersion;
    bool m_PriorVersionIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SendigDatasetVariableLinks_H_ */
