/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ExportCdashClassVariablesRow

class ExportCdashClassVariablesRowTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExportCdashClassVariablesRow
        //val modelInstance = ExportCdashClassVariablesRow()

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `propertyClass`
        should("test propertyClass") {
            // uncomment below to test the property
            //modelInstance.propertyClass shouldBe ("TODO")
        }

        // to test the property `domain`
        should("test domain") {
            // uncomment below to test the property
            //modelInstance.domain shouldBe ("TODO")
        }

        // to test the property `variableOrder`
        should("test variableOrder") {
            // uncomment below to test the property
            //modelInstance.variableOrder shouldBe ("TODO")
        }

        // to test the property `cdASHVariable`
        should("test cdASHVariable") {
            // uncomment below to test the property
            //modelInstance.cdASHVariable shouldBe ("TODO")
        }

        // to test the property `cdASHVariableLabel`
        should("test cdASHVariableLabel") {
            // uncomment below to test the property
            //modelInstance.cdASHVariableLabel shouldBe ("TODO")
        }

        // to test the property `drAFTCDASHDefinition`
        should("test drAFTCDASHDefinition") {
            // uncomment below to test the property
            //modelInstance.drAFTCDASHDefinition shouldBe ("TODO")
        }

        // to test the property `domainSpecific`
        should("test domainSpecific") {
            // uncomment below to test the property
            //modelInstance.domainSpecific shouldBe ("TODO")
        }

        // to test the property `questionText`
        should("test questionText") {
            // uncomment below to test the property
            //modelInstance.questionText shouldBe ("TODO")
        }

        // to test the property `prompt`
        should("test prompt") {
            // uncomment below to test the property
            //modelInstance.prompt shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `sdTMTarget`
        should("test sdTMTarget") {
            // uncomment below to test the property
            //modelInstance.sdTMTarget shouldBe ("TODO")
        }

        // to test the property `mappingInstructions`
        should("test mappingInstructions") {
            // uncomment below to test the property
            //modelInstance.mappingInstructions shouldBe ("TODO")
        }

        // to test the property `controlledTerminologyCodelistName`
        should("test controlledTerminologyCodelistName") {
            // uncomment below to test the property
            //modelInstance.controlledTerminologyCodelistName shouldBe ("TODO")
        }

        // to test the property `implementationNotes`
        should("test implementationNotes") {
            // uncomment below to test the property
            //modelInstance.implementationNotes shouldBe ("TODO")
        }

    }
}
