/*
CDISC Library API

REST API Documentation for CDISC Library in production server

API version: 1.1.0
Contact: cdisc_library_support@cdisc.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the XmlCdashProductClasses type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &XmlCdashProductClasses{}

// XmlCdashProductClasses struct for XmlCdashProductClasses
type XmlCdashProductClasses struct {
	Self *CdashProductClasses `json:"self,omitempty"`
}

// NewXmlCdashProductClasses instantiates a new XmlCdashProductClasses object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewXmlCdashProductClasses() *XmlCdashProductClasses {
	this := XmlCdashProductClasses{}
	return &this
}

// NewXmlCdashProductClassesWithDefaults instantiates a new XmlCdashProductClasses object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewXmlCdashProductClassesWithDefaults() *XmlCdashProductClasses {
	this := XmlCdashProductClasses{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *XmlCdashProductClasses) GetSelf() CdashProductClasses {
	if o == nil || IsNil(o.Self) {
		var ret CdashProductClasses
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *XmlCdashProductClasses) GetSelfOk() (*CdashProductClasses, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *XmlCdashProductClasses) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given CdashProductClasses and assigns it to the Self field.
func (o *XmlCdashProductClasses) SetSelf(v CdashProductClasses) {
	o.Self = &v
}

func (o XmlCdashProductClasses) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o XmlCdashProductClasses) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	return toSerialize, nil
}

type NullableXmlCdashProductClasses struct {
	value *XmlCdashProductClasses
	isSet bool
}

func (v NullableXmlCdashProductClasses) Get() *XmlCdashProductClasses {
	return v.value
}

func (v *NullableXmlCdashProductClasses) Set(val *XmlCdashProductClasses) {
	v.value = val
	v.isSet = true
}

func (v NullableXmlCdashProductClasses) IsSet() bool {
	return v.isSet
}

func (v *NullableXmlCdashProductClasses) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableXmlCdashProductClasses(val *XmlCdashProductClasses) *NullableXmlCdashProductClasses {
	return &NullableXmlCdashProductClasses{value: val, isSet: true}
}

func (v NullableXmlCdashProductClasses) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableXmlCdashProductClasses) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


