/*
CDISC Library API

REST API Documentation for CDISC Library in production server

API version: 1.1.0
Contact: cdisc_library_support@cdisc.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SdtmigClass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SdtmigClass{}

// SdtmigClass struct for SdtmigClass
type SdtmigClass struct {
	Ordinal *string `json:"ordinal,omitempty"`
	Name *string `json:"name,omitempty"`
	Label *string `json:"label,omitempty"`
	Description *string `json:"description,omitempty"`
	Links *SdtmigClassLinks `json:"_links,omitempty"`
	Datasets []SdtmigDataset `json:"datasets,omitempty"`
}

// NewSdtmigClass instantiates a new SdtmigClass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSdtmigClass() *SdtmigClass {
	this := SdtmigClass{}
	return &this
}

// NewSdtmigClassWithDefaults instantiates a new SdtmigClass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSdtmigClassWithDefaults() *SdtmigClass {
	this := SdtmigClass{}
	return &this
}

// GetOrdinal returns the Ordinal field value if set, zero value otherwise.
func (o *SdtmigClass) GetOrdinal() string {
	if o == nil || IsNil(o.Ordinal) {
		var ret string
		return ret
	}
	return *o.Ordinal
}

// GetOrdinalOk returns a tuple with the Ordinal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdtmigClass) GetOrdinalOk() (*string, bool) {
	if o == nil || IsNil(o.Ordinal) {
		return nil, false
	}
	return o.Ordinal, true
}

// HasOrdinal returns a boolean if a field has been set.
func (o *SdtmigClass) HasOrdinal() bool {
	if o != nil && !IsNil(o.Ordinal) {
		return true
	}

	return false
}

// SetOrdinal gets a reference to the given string and assigns it to the Ordinal field.
func (o *SdtmigClass) SetOrdinal(v string) {
	o.Ordinal = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SdtmigClass) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdtmigClass) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SdtmigClass) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SdtmigClass) SetName(v string) {
	o.Name = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *SdtmigClass) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdtmigClass) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *SdtmigClass) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *SdtmigClass) SetLabel(v string) {
	o.Label = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SdtmigClass) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdtmigClass) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SdtmigClass) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SdtmigClass) SetDescription(v string) {
	o.Description = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *SdtmigClass) GetLinks() SdtmigClassLinks {
	if o == nil || IsNil(o.Links) {
		var ret SdtmigClassLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdtmigClass) GetLinksOk() (*SdtmigClassLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *SdtmigClass) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given SdtmigClassLinks and assigns it to the Links field.
func (o *SdtmigClass) SetLinks(v SdtmigClassLinks) {
	o.Links = &v
}

// GetDatasets returns the Datasets field value if set, zero value otherwise.
func (o *SdtmigClass) GetDatasets() []SdtmigDataset {
	if o == nil || IsNil(o.Datasets) {
		var ret []SdtmigDataset
		return ret
	}
	return o.Datasets
}

// GetDatasetsOk returns a tuple with the Datasets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdtmigClass) GetDatasetsOk() ([]SdtmigDataset, bool) {
	if o == nil || IsNil(o.Datasets) {
		return nil, false
	}
	return o.Datasets, true
}

// HasDatasets returns a boolean if a field has been set.
func (o *SdtmigClass) HasDatasets() bool {
	if o != nil && !IsNil(o.Datasets) {
		return true
	}

	return false
}

// SetDatasets gets a reference to the given []SdtmigDataset and assigns it to the Datasets field.
func (o *SdtmigClass) SetDatasets(v []SdtmigDataset) {
	o.Datasets = v
}

func (o SdtmigClass) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SdtmigClass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ordinal) {
		toSerialize["ordinal"] = o.Ordinal
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	if !IsNil(o.Datasets) {
		toSerialize["datasets"] = o.Datasets
	}
	return toSerialize, nil
}

type NullableSdtmigClass struct {
	value *SdtmigClass
	isSet bool
}

func (v NullableSdtmigClass) Get() *SdtmigClass {
	return v.value
}

func (v *NullableSdtmigClass) Set(val *SdtmigClass) {
	v.value = val
	v.isSet = true
}

func (v NullableSdtmigClass) IsSet() bool {
	return v.isSet
}

func (v *NullableSdtmigClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSdtmigClass(val *SdtmigClass) *NullableSdtmigClass {
	return &NullableSdtmigClass{value: val, isSet: true}
}

func (v NullableSdtmigClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSdtmigClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


