/*
CDISC Library API

REST API Documentation for CDISC Library in production server

API version: 1.1.0
Contact: cdisc_library_support@cdisc.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CdashigProductDomainsLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CdashigProductDomainsLinks{}

// CdashigProductDomainsLinks struct for CdashigProductDomainsLinks
type CdashigProductDomainsLinks struct {
	Self *CdashigProductDomainsRef `json:"self,omitempty"`
	ParentProduct *CdashigProductRef `json:"parentProduct,omitempty"`
	Domains []CdashigDomainRefElement `json:"domains,omitempty"`
}

// NewCdashigProductDomainsLinks instantiates a new CdashigProductDomainsLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdashigProductDomainsLinks() *CdashigProductDomainsLinks {
	this := CdashigProductDomainsLinks{}
	return &this
}

// NewCdashigProductDomainsLinksWithDefaults instantiates a new CdashigProductDomainsLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdashigProductDomainsLinksWithDefaults() *CdashigProductDomainsLinks {
	this := CdashigProductDomainsLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *CdashigProductDomainsLinks) GetSelf() CdashigProductDomainsRef {
	if o == nil || IsNil(o.Self) {
		var ret CdashigProductDomainsRef
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdashigProductDomainsLinks) GetSelfOk() (*CdashigProductDomainsRef, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *CdashigProductDomainsLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given CdashigProductDomainsRef and assigns it to the Self field.
func (o *CdashigProductDomainsLinks) SetSelf(v CdashigProductDomainsRef) {
	o.Self = &v
}

// GetParentProduct returns the ParentProduct field value if set, zero value otherwise.
func (o *CdashigProductDomainsLinks) GetParentProduct() CdashigProductRef {
	if o == nil || IsNil(o.ParentProduct) {
		var ret CdashigProductRef
		return ret
	}
	return *o.ParentProduct
}

// GetParentProductOk returns a tuple with the ParentProduct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdashigProductDomainsLinks) GetParentProductOk() (*CdashigProductRef, bool) {
	if o == nil || IsNil(o.ParentProduct) {
		return nil, false
	}
	return o.ParentProduct, true
}

// HasParentProduct returns a boolean if a field has been set.
func (o *CdashigProductDomainsLinks) HasParentProduct() bool {
	if o != nil && !IsNil(o.ParentProduct) {
		return true
	}

	return false
}

// SetParentProduct gets a reference to the given CdashigProductRef and assigns it to the ParentProduct field.
func (o *CdashigProductDomainsLinks) SetParentProduct(v CdashigProductRef) {
	o.ParentProduct = &v
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *CdashigProductDomainsLinks) GetDomains() []CdashigDomainRefElement {
	if o == nil || IsNil(o.Domains) {
		var ret []CdashigDomainRefElement
		return ret
	}
	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdashigProductDomainsLinks) GetDomainsOk() ([]CdashigDomainRefElement, bool) {
	if o == nil || IsNil(o.Domains) {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *CdashigProductDomainsLinks) HasDomains() bool {
	if o != nil && !IsNil(o.Domains) {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []CdashigDomainRefElement and assigns it to the Domains field.
func (o *CdashigProductDomainsLinks) SetDomains(v []CdashigDomainRefElement) {
	o.Domains = v
}

func (o CdashigProductDomainsLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CdashigProductDomainsLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	if !IsNil(o.ParentProduct) {
		toSerialize["parentProduct"] = o.ParentProduct
	}
	if !IsNil(o.Domains) {
		toSerialize["domains"] = o.Domains
	}
	return toSerialize, nil
}

type NullableCdashigProductDomainsLinks struct {
	value *CdashigProductDomainsLinks
	isSet bool
}

func (v NullableCdashigProductDomainsLinks) Get() *CdashigProductDomainsLinks {
	return v.value
}

func (v *NullableCdashigProductDomainsLinks) Set(val *CdashigProductDomainsLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableCdashigProductDomainsLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableCdashigProductDomainsLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdashigProductDomainsLinks(val *CdashigProductDomainsLinks) *NullableCdashigProductDomainsLinks {
	return &NullableCdashigProductDomainsLinks{value: val, isSet: true}
}

func (v NullableCdashigProductDomainsLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdashigProductDomainsLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


