/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICtPackagesLinks.h
 *
 * 
 */

#ifndef OAICtPackagesLinks_H
#define OAICtPackagesLinks_H

#include <QJsonObject>

#include "OAICtPackageRefElement.h"
#include "OAICtPackagesRef.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAICtPackagesRef;
class OAICtPackageRefElement;

class OAICtPackagesLinks : public OAIObject {
public:
    OAICtPackagesLinks();
    OAICtPackagesLinks(QString json);
    ~OAICtPackagesLinks() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAICtPackagesRef getSelf() const;
    void setSelf(const OAICtPackagesRef &self);
    bool is_self_Set() const;
    bool is_self_Valid() const;

    QList<OAICtPackageRefElement> getPackages() const;
    void setPackages(const QList<OAICtPackageRefElement> &packages);
    bool is_packages_Set() const;
    bool is_packages_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAICtPackagesRef m_self;
    bool m_self_isSet;
    bool m_self_isValid;

    QList<OAICtPackageRefElement> m_packages;
    bool m_packages_isSet;
    bool m_packages_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAICtPackagesLinks)

#endif // OAICtPackagesLinks_H
