/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIRootSdtmDatasetVariable.h
 *
 * 
 */

#ifndef OAIRootSdtmDatasetVariable_H
#define OAIRootSdtmDatasetVariable_H

#include <QJsonObject>

#include "OAIRootSdtmDatasetVariableLinks.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIRootSdtmDatasetVariableLinks;

class OAIRootSdtmDatasetVariable : public OAIObject {
public:
    OAIRootSdtmDatasetVariable();
    OAIRootSdtmDatasetVariable(QString json);
    ~OAIRootSdtmDatasetVariable() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIRootSdtmDatasetVariableLinks getLinks() const;
    void setLinks(const OAIRootSdtmDatasetVariableLinks &_links);
    bool is__links_Set() const;
    bool is__links_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIRootSdtmDatasetVariableLinks m__links;
    bool m__links_isSet;
    bool m__links_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIRootSdtmDatasetVariable)

#endif // OAIRootSdtmDatasetVariable_H
