/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISdtmDatasetVariableLinks.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAISdtmDatasetVariableLinks::OAISdtmDatasetVariableLinks(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISdtmDatasetVariableLinks::OAISdtmDatasetVariableLinks() {
    this->initializeModel();
}

OAISdtmDatasetVariableLinks::~OAISdtmDatasetVariableLinks() {}

void OAISdtmDatasetVariableLinks::initializeModel() {

    m_self_isSet = false;
    m_self_isValid = false;

    m_parent_product_isSet = false;
    m_parent_product_isValid = false;

    m_parent_dataset_isSet = false;
    m_parent_dataset_isValid = false;

    m_root_item_isSet = false;
    m_root_item_isValid = false;

    m_prior_version_isSet = false;
    m_prior_version_isValid = false;
}

void OAISdtmDatasetVariableLinks::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISdtmDatasetVariableLinks::fromJsonObject(QJsonObject json) {

    m_self_isValid = ::OpenAPI::fromJsonValue(m_self, json[QString("self")]);
    m_self_isSet = !json[QString("self")].isNull() && m_self_isValid;

    m_parent_product_isValid = ::OpenAPI::fromJsonValue(m_parent_product, json[QString("parentProduct")]);
    m_parent_product_isSet = !json[QString("parentProduct")].isNull() && m_parent_product_isValid;

    m_parent_dataset_isValid = ::OpenAPI::fromJsonValue(m_parent_dataset, json[QString("parentDataset")]);
    m_parent_dataset_isSet = !json[QString("parentDataset")].isNull() && m_parent_dataset_isValid;

    m_root_item_isValid = ::OpenAPI::fromJsonValue(m_root_item, json[QString("rootItem")]);
    m_root_item_isSet = !json[QString("rootItem")].isNull() && m_root_item_isValid;

    m_prior_version_isValid = ::OpenAPI::fromJsonValue(m_prior_version, json[QString("priorVersion")]);
    m_prior_version_isSet = !json[QString("priorVersion")].isNull() && m_prior_version_isValid;
}

QString OAISdtmDatasetVariableLinks::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISdtmDatasetVariableLinks::asJsonObject() const {
    QJsonObject obj;
    if (m_self.isSet()) {
        obj.insert(QString("self"), ::OpenAPI::toJsonValue(m_self));
    }
    if (m_parent_product.isSet()) {
        obj.insert(QString("parentProduct"), ::OpenAPI::toJsonValue(m_parent_product));
    }
    if (m_parent_dataset.isSet()) {
        obj.insert(QString("parentDataset"), ::OpenAPI::toJsonValue(m_parent_dataset));
    }
    if (m_root_item.isSet()) {
        obj.insert(QString("rootItem"), ::OpenAPI::toJsonValue(m_root_item));
    }
    if (m_prior_version.isSet()) {
        obj.insert(QString("priorVersion"), ::OpenAPI::toJsonValue(m_prior_version));
    }
    return obj;
}

OAISdtmDatasetVariableRef OAISdtmDatasetVariableLinks::getSelf() const {
    return m_self;
}
void OAISdtmDatasetVariableLinks::setSelf(const OAISdtmDatasetVariableRef &self) {
    m_self = self;
    m_self_isSet = true;
}

bool OAISdtmDatasetVariableLinks::is_self_Set() const{
    return m_self_isSet;
}

bool OAISdtmDatasetVariableLinks::is_self_Valid() const{
    return m_self_isValid;
}

OAISdtmProductRef OAISdtmDatasetVariableLinks::getParentProduct() const {
    return m_parent_product;
}
void OAISdtmDatasetVariableLinks::setParentProduct(const OAISdtmProductRef &parent_product) {
    m_parent_product = parent_product;
    m_parent_product_isSet = true;
}

bool OAISdtmDatasetVariableLinks::is_parent_product_Set() const{
    return m_parent_product_isSet;
}

bool OAISdtmDatasetVariableLinks::is_parent_product_Valid() const{
    return m_parent_product_isValid;
}

OAISdtmDatasetRef OAISdtmDatasetVariableLinks::getParentDataset() const {
    return m_parent_dataset;
}
void OAISdtmDatasetVariableLinks::setParentDataset(const OAISdtmDatasetRef &parent_dataset) {
    m_parent_dataset = parent_dataset;
    m_parent_dataset_isSet = true;
}

bool OAISdtmDatasetVariableLinks::is_parent_dataset_Set() const{
    return m_parent_dataset_isSet;
}

bool OAISdtmDatasetVariableLinks::is_parent_dataset_Valid() const{
    return m_parent_dataset_isValid;
}

OAIRootSdtmDatasetVariableRef OAISdtmDatasetVariableLinks::getRootItem() const {
    return m_root_item;
}
void OAISdtmDatasetVariableLinks::setRootItem(const OAIRootSdtmDatasetVariableRef &root_item) {
    m_root_item = root_item;
    m_root_item_isSet = true;
}

bool OAISdtmDatasetVariableLinks::is_root_item_Set() const{
    return m_root_item_isSet;
}

bool OAISdtmDatasetVariableLinks::is_root_item_Valid() const{
    return m_root_item_isValid;
}

OAISdtmDatasetVariableRef OAISdtmDatasetVariableLinks::getPriorVersion() const {
    return m_prior_version;
}
void OAISdtmDatasetVariableLinks::setPriorVersion(const OAISdtmDatasetVariableRef &prior_version) {
    m_prior_version = prior_version;
    m_prior_version_isSet = true;
}

bool OAISdtmDatasetVariableLinks::is_prior_version_Set() const{
    return m_prior_version_isSet;
}

bool OAISdtmDatasetVariableLinks::is_prior_version_Valid() const{
    return m_prior_version_isValid;
}

bool OAISdtmDatasetVariableLinks::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_self.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_parent_product.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_parent_dataset.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_root_item.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_prior_version.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISdtmDatasetVariableLinks::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
