/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISdtmigDatasetVariableLinks.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAISdtmigDatasetVariableLinks::OAISdtmigDatasetVariableLinks(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISdtmigDatasetVariableLinks::OAISdtmigDatasetVariableLinks() {
    this->initializeModel();
}

OAISdtmigDatasetVariableLinks::~OAISdtmigDatasetVariableLinks() {}

void OAISdtmigDatasetVariableLinks::initializeModel() {

    m_self_isSet = false;
    m_self_isValid = false;

    m_codelist_isSet = false;
    m_codelist_isValid = false;

    m_model_class_variable_isSet = false;
    m_model_class_variable_isValid = false;

    m_model_dataset_variable_isSet = false;
    m_model_dataset_variable_isValid = false;

    m_parent_product_isSet = false;
    m_parent_product_isValid = false;

    m_parent_dataset_isSet = false;
    m_parent_dataset_isValid = false;

    m_root_item_isSet = false;
    m_root_item_isValid = false;

    m_prior_version_isSet = false;
    m_prior_version_isValid = false;
}

void OAISdtmigDatasetVariableLinks::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISdtmigDatasetVariableLinks::fromJsonObject(QJsonObject json) {

    m_self_isValid = ::OpenAPI::fromJsonValue(m_self, json[QString("self")]);
    m_self_isSet = !json[QString("self")].isNull() && m_self_isValid;

    m_codelist_isValid = ::OpenAPI::fromJsonValue(m_codelist, json[QString("codelist")]);
    m_codelist_isSet = !json[QString("codelist")].isNull() && m_codelist_isValid;

    m_model_class_variable_isValid = ::OpenAPI::fromJsonValue(m_model_class_variable, json[QString("modelClassVariable")]);
    m_model_class_variable_isSet = !json[QString("modelClassVariable")].isNull() && m_model_class_variable_isValid;

    m_model_dataset_variable_isValid = ::OpenAPI::fromJsonValue(m_model_dataset_variable, json[QString("modelDatasetVariable")]);
    m_model_dataset_variable_isSet = !json[QString("modelDatasetVariable")].isNull() && m_model_dataset_variable_isValid;

    m_parent_product_isValid = ::OpenAPI::fromJsonValue(m_parent_product, json[QString("parentProduct")]);
    m_parent_product_isSet = !json[QString("parentProduct")].isNull() && m_parent_product_isValid;

    m_parent_dataset_isValid = ::OpenAPI::fromJsonValue(m_parent_dataset, json[QString("parentDataset")]);
    m_parent_dataset_isSet = !json[QString("parentDataset")].isNull() && m_parent_dataset_isValid;

    m_root_item_isValid = ::OpenAPI::fromJsonValue(m_root_item, json[QString("rootItem")]);
    m_root_item_isSet = !json[QString("rootItem")].isNull() && m_root_item_isValid;

    m_prior_version_isValid = ::OpenAPI::fromJsonValue(m_prior_version, json[QString("priorVersion")]);
    m_prior_version_isSet = !json[QString("priorVersion")].isNull() && m_prior_version_isValid;
}

QString OAISdtmigDatasetVariableLinks::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISdtmigDatasetVariableLinks::asJsonObject() const {
    QJsonObject obj;
    if (m_self.isSet()) {
        obj.insert(QString("self"), ::OpenAPI::toJsonValue(m_self));
    }
    if (m_codelist.size() > 0) {
        obj.insert(QString("codelist"), ::OpenAPI::toJsonValue(m_codelist));
    }
    if (m_model_class_variable.isSet()) {
        obj.insert(QString("modelClassVariable"), ::OpenAPI::toJsonValue(m_model_class_variable));
    }
    if (m_model_dataset_variable.isSet()) {
        obj.insert(QString("modelDatasetVariable"), ::OpenAPI::toJsonValue(m_model_dataset_variable));
    }
    if (m_parent_product.isSet()) {
        obj.insert(QString("parentProduct"), ::OpenAPI::toJsonValue(m_parent_product));
    }
    if (m_parent_dataset.isSet()) {
        obj.insert(QString("parentDataset"), ::OpenAPI::toJsonValue(m_parent_dataset));
    }
    if (m_root_item.isSet()) {
        obj.insert(QString("rootItem"), ::OpenAPI::toJsonValue(m_root_item));
    }
    if (m_prior_version.isSet()) {
        obj.insert(QString("priorVersion"), ::OpenAPI::toJsonValue(m_prior_version));
    }
    return obj;
}

OAISdtmigDatasetVariableRef OAISdtmigDatasetVariableLinks::getSelf() const {
    return m_self;
}
void OAISdtmigDatasetVariableLinks::setSelf(const OAISdtmigDatasetVariableRef &self) {
    m_self = self;
    m_self_isSet = true;
}

bool OAISdtmigDatasetVariableLinks::is_self_Set() const{
    return m_self_isSet;
}

bool OAISdtmigDatasetVariableLinks::is_self_Valid() const{
    return m_self_isValid;
}

QList<OAIRootCtCodelistRefElement> OAISdtmigDatasetVariableLinks::getCodelist() const {
    return m_codelist;
}
void OAISdtmigDatasetVariableLinks::setCodelist(const QList<OAIRootCtCodelistRefElement> &codelist) {
    m_codelist = codelist;
    m_codelist_isSet = true;
}

bool OAISdtmigDatasetVariableLinks::is_codelist_Set() const{
    return m_codelist_isSet;
}

bool OAISdtmigDatasetVariableLinks::is_codelist_Valid() const{
    return m_codelist_isValid;
}

OAISdtmClassVariableRef OAISdtmigDatasetVariableLinks::getModelClassVariable() const {
    return m_model_class_variable;
}
void OAISdtmigDatasetVariableLinks::setModelClassVariable(const OAISdtmClassVariableRef &model_class_variable) {
    m_model_class_variable = model_class_variable;
    m_model_class_variable_isSet = true;
}

bool OAISdtmigDatasetVariableLinks::is_model_class_variable_Set() const{
    return m_model_class_variable_isSet;
}

bool OAISdtmigDatasetVariableLinks::is_model_class_variable_Valid() const{
    return m_model_class_variable_isValid;
}

OAISdtmDatasetVariableRef OAISdtmigDatasetVariableLinks::getModelDatasetVariable() const {
    return m_model_dataset_variable;
}
void OAISdtmigDatasetVariableLinks::setModelDatasetVariable(const OAISdtmDatasetVariableRef &model_dataset_variable) {
    m_model_dataset_variable = model_dataset_variable;
    m_model_dataset_variable_isSet = true;
}

bool OAISdtmigDatasetVariableLinks::is_model_dataset_variable_Set() const{
    return m_model_dataset_variable_isSet;
}

bool OAISdtmigDatasetVariableLinks::is_model_dataset_variable_Valid() const{
    return m_model_dataset_variable_isValid;
}

OAISdtmigProductRef OAISdtmigDatasetVariableLinks::getParentProduct() const {
    return m_parent_product;
}
void OAISdtmigDatasetVariableLinks::setParentProduct(const OAISdtmigProductRef &parent_product) {
    m_parent_product = parent_product;
    m_parent_product_isSet = true;
}

bool OAISdtmigDatasetVariableLinks::is_parent_product_Set() const{
    return m_parent_product_isSet;
}

bool OAISdtmigDatasetVariableLinks::is_parent_product_Valid() const{
    return m_parent_product_isValid;
}

OAISdtmigDatasetRef OAISdtmigDatasetVariableLinks::getParentDataset() const {
    return m_parent_dataset;
}
void OAISdtmigDatasetVariableLinks::setParentDataset(const OAISdtmigDatasetRef &parent_dataset) {
    m_parent_dataset = parent_dataset;
    m_parent_dataset_isSet = true;
}

bool OAISdtmigDatasetVariableLinks::is_parent_dataset_Set() const{
    return m_parent_dataset_isSet;
}

bool OAISdtmigDatasetVariableLinks::is_parent_dataset_Valid() const{
    return m_parent_dataset_isValid;
}

OAIRootSdtmigDatasetVariableRef OAISdtmigDatasetVariableLinks::getRootItem() const {
    return m_root_item;
}
void OAISdtmigDatasetVariableLinks::setRootItem(const OAIRootSdtmigDatasetVariableRef &root_item) {
    m_root_item = root_item;
    m_root_item_isSet = true;
}

bool OAISdtmigDatasetVariableLinks::is_root_item_Set() const{
    return m_root_item_isSet;
}

bool OAISdtmigDatasetVariableLinks::is_root_item_Valid() const{
    return m_root_item_isValid;
}

OAISdtmigDatasetVariableRef OAISdtmigDatasetVariableLinks::getPriorVersion() const {
    return m_prior_version;
}
void OAISdtmigDatasetVariableLinks::setPriorVersion(const OAISdtmigDatasetVariableRef &prior_version) {
    m_prior_version = prior_version;
    m_prior_version_isSet = true;
}

bool OAISdtmigDatasetVariableLinks::is_prior_version_Set() const{
    return m_prior_version_isSet;
}

bool OAISdtmigDatasetVariableLinks::is_prior_version_Valid() const{
    return m_prior_version_isValid;
}

bool OAISdtmigDatasetVariableLinks::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_self.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_codelist.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_model_class_variable.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_model_dataset_variable.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_parent_product.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_parent_dataset.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_root_item.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_prior_version.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISdtmigDatasetVariableLinks::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
