/*
CDISC Library API

REST API Documentation for CDISC Library in production server

API version: 1.1.0
Contact: cdisc_library_support@cdisc.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the XmlAdamProductDatastructures type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &XmlAdamProductDatastructures{}

// XmlAdamProductDatastructures struct for XmlAdamProductDatastructures
type XmlAdamProductDatastructures struct {
	Self *AdamProductDatastructures `json:"self,omitempty"`
}

// NewXmlAdamProductDatastructures instantiates a new XmlAdamProductDatastructures object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewXmlAdamProductDatastructures() *XmlAdamProductDatastructures {
	this := XmlAdamProductDatastructures{}
	return &this
}

// NewXmlAdamProductDatastructuresWithDefaults instantiates a new XmlAdamProductDatastructures object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewXmlAdamProductDatastructuresWithDefaults() *XmlAdamProductDatastructures {
	this := XmlAdamProductDatastructures{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *XmlAdamProductDatastructures) GetSelf() AdamProductDatastructures {
	if o == nil || IsNil(o.Self) {
		var ret AdamProductDatastructures
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *XmlAdamProductDatastructures) GetSelfOk() (*AdamProductDatastructures, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *XmlAdamProductDatastructures) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given AdamProductDatastructures and assigns it to the Self field.
func (o *XmlAdamProductDatastructures) SetSelf(v AdamProductDatastructures) {
	o.Self = &v
}

func (o XmlAdamProductDatastructures) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o XmlAdamProductDatastructures) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	return toSerialize, nil
}

type NullableXmlAdamProductDatastructures struct {
	value *XmlAdamProductDatastructures
	isSet bool
}

func (v NullableXmlAdamProductDatastructures) Get() *XmlAdamProductDatastructures {
	return v.value
}

func (v *NullableXmlAdamProductDatastructures) Set(val *XmlAdamProductDatastructures) {
	v.value = val
	v.isSet = true
}

func (v NullableXmlAdamProductDatastructures) IsSet() bool {
	return v.isSet
}

func (v *NullableXmlAdamProductDatastructures) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableXmlAdamProductDatastructures(val *XmlAdamProductDatastructures) *NullableXmlAdamProductDatastructures {
	return &NullableXmlAdamProductDatastructures{value: val, isSet: true}
}

func (v NullableXmlAdamProductDatastructures) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableXmlAdamProductDatastructures) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


