//
// ExportAdamVariablesTable.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ExportAdamVariablesTable: Codable {
    public var variables: [ExportAdamVariablesRow]?

    public init(variables: [ExportAdamVariablesRow]? = nil) {
        self.variables = variables
    }
}
