//
// XmlCdashClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct XmlCdashClass: Codable {
    public var _self: CdashClass?

    public init(_self: CdashClass? = nil) {
        self._self = _self
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _self = "self"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        _self = try container.decodeIfPresent(CdashClass.self, forKey: ._self)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_self, forKey: ._self)
    }
}
