# coding: utf-8

"""
    CDISC Library API

    REST API Documentation for CDISC Library in production server

    The version of the OpenAPI document: 1.1.0
    Contact: cdisc_library_support@cdisc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from openapi_client.models.cdash_domain_field import CdashDomainField
from openapi_client.models.cdash_domain_links import CdashDomainLinks

class CdashDomain(BaseModel):
    """
    CdashDomain
    """
    ordinal: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    links: Optional[CdashDomainLinks] = Field(default=None, alias="_links")
    fields: Optional[conlist(CdashDomainField)] = None
    __properties = ["ordinal", "name", "label", "_links", "fields"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CdashDomain:
        """Create an instance of CdashDomain from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['_links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list)
        _items = []
        if self.fields:
            for _item in self.fields:
                if _item:
                    _items.append(_item.to_dict())
            _dict['fields'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CdashDomain:
        """Create an instance of CdashDomain from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CdashDomain.parse_obj(obj)

        _obj = CdashDomain.parse_obj({
            "ordinal": obj.get("ordinal"),
            "name": obj.get("name"),
            "label": obj.get("label"),
            "links": CdashDomainLinks.from_dict(obj.get("_links")) if obj.get("_links") is not None else None,
            "fields": [CdashDomainField.from_dict(_item) for _item in obj.get("fields")] if obj.get("fields") is not None else None
        })
        return _obj


