/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.16.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/SdtmigDataset.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SdtmigDataset::SdtmigDataset()
{
    m_Ordinal = utility::conversions::to_string_t("");
    m_OrdinalIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Label = utility::conversions::to_string_t("");
    m_LabelIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_DatasetStructure = utility::conversions::to_string_t("");
    m_DatasetStructureIsSet = false;
    m__linksIsSet = false;
    m_DatasetVariablesIsSet = false;
}

SdtmigDataset::~SdtmigDataset()
{
}

void SdtmigDataset::validate()
{
    // TODO: implement validation
}

web::json::value SdtmigDataset::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_OrdinalIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("ordinal"))] = ModelBase::toJson(m_Ordinal);
    }
    if(m_NameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_LabelIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("label"))] = ModelBase::toJson(m_Label);
    }
    if(m_DescriptionIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_DatasetStructureIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("datasetStructure"))] = ModelBase::toJson(m_DatasetStructure);
    }
    if(m__linksIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("_links"))] = ModelBase::toJson(m__links);
    }
    if(m_DatasetVariablesIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("datasetVariables"))] = ModelBase::toJson(m_DatasetVariables);
    }

    return val;
}

bool SdtmigDataset::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("ordinal"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("ordinal")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOrdinal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOrdinal);
            setOrdinal(refVal_setOrdinal);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("label"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("label")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLabel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLabel);
            setLabel(refVal_setLabel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("datasetStructure"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("datasetStructure")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDatasetStructure;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDatasetStructure);
            setDatasetStructure(refVal_setDatasetStructure);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("_links"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("_links")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<SdtmigDatasetLinks> refVal_setLinks;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLinks);
            setLinks(refVal_setLinks);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("datasetVariables"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("datasetVariables")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<SdtmigDatasetVariable>> refVal_setDatasetVariables;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDatasetVariables);
            setDatasetVariables(refVal_setDatasetVariables);
            
        }
    }
    return ok;
}

void SdtmigDataset::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_OrdinalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("ordinal")), m_Ordinal));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_LabelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("label")), m_Label));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_DatasetStructureIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("datasetStructure")), m_DatasetStructure));
    }
    if(m__linksIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("_links")), m__links));
    }
    if(m_DatasetVariablesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("datasetVariables")), m_DatasetVariables));
    }
}

bool SdtmigDataset::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("ordinal"))))
    {
        utility::string_t refVal_setOrdinal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("ordinal"))), refVal_setOrdinal );
        setOrdinal(refVal_setOrdinal);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("label"))))
    {
        utility::string_t refVal_setLabel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("label"))), refVal_setLabel );
        setLabel(refVal_setLabel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("datasetStructure"))))
    {
        utility::string_t refVal_setDatasetStructure;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("datasetStructure"))), refVal_setDatasetStructure );
        setDatasetStructure(refVal_setDatasetStructure);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("_links"))))
    {
        std::shared_ptr<SdtmigDatasetLinks> refVal_setLinks;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("_links"))), refVal_setLinks );
        setLinks(refVal_setLinks);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("datasetVariables"))))
    {
        std::vector<std::shared_ptr<SdtmigDatasetVariable>> refVal_setDatasetVariables;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("datasetVariables"))), refVal_setDatasetVariables );
        setDatasetVariables(refVal_setDatasetVariables);
    }
    return ok;
}


utility::string_t SdtmigDataset::getOrdinal() const
{
    return m_Ordinal;
}


void SdtmigDataset::setOrdinal(const utility::string_t& value)
{
    m_Ordinal = value;
    m_OrdinalIsSet = true;
}

bool SdtmigDataset::ordinalIsSet() const
{
    return m_OrdinalIsSet;
}

void SdtmigDataset::unsetOrdinal()
{
    m_OrdinalIsSet = false;
}
utility::string_t SdtmigDataset::getName() const
{
    return m_Name;
}


void SdtmigDataset::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool SdtmigDataset::nameIsSet() const
{
    return m_NameIsSet;
}

void SdtmigDataset::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t SdtmigDataset::getLabel() const
{
    return m_Label;
}


void SdtmigDataset::setLabel(const utility::string_t& value)
{
    m_Label = value;
    m_LabelIsSet = true;
}

bool SdtmigDataset::labelIsSet() const
{
    return m_LabelIsSet;
}

void SdtmigDataset::unsetLabel()
{
    m_LabelIsSet = false;
}
utility::string_t SdtmigDataset::getDescription() const
{
    return m_Description;
}


void SdtmigDataset::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool SdtmigDataset::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void SdtmigDataset::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t SdtmigDataset::getDatasetStructure() const
{
    return m_DatasetStructure;
}


void SdtmigDataset::setDatasetStructure(const utility::string_t& value)
{
    m_DatasetStructure = value;
    m_DatasetStructureIsSet = true;
}

bool SdtmigDataset::datasetStructureIsSet() const
{
    return m_DatasetStructureIsSet;
}

void SdtmigDataset::unsetDatasetStructure()
{
    m_DatasetStructureIsSet = false;
}
std::shared_ptr<SdtmigDatasetLinks> SdtmigDataset::getLinks() const
{
    return m__links;
}


void SdtmigDataset::setLinks(const std::shared_ptr<SdtmigDatasetLinks>& value)
{
    m__links = value;
    m__linksIsSet = true;
}

bool SdtmigDataset::linksIsSet() const
{
    return m__linksIsSet;
}

void SdtmigDataset::unset_links()
{
    m__linksIsSet = false;
}
std::vector<std::shared_ptr<SdtmigDatasetVariable>> SdtmigDataset::getDatasetVariables() const
{
    return m_DatasetVariables;
}


void SdtmigDataset::setDatasetVariables(const std::vector<std::shared_ptr<SdtmigDatasetVariable>>& value)
{
    m_DatasetVariables = value;
    m_DatasetVariablesIsSet = true;
}

bool SdtmigDataset::datasetVariablesIsSet() const
{
    return m_DatasetVariablesIsSet;
}

void SdtmigDataset::unsetDatasetVariables()
{
    m_DatasetVariablesIsSet = false;
}

}
}
}
}


