/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.16.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/XmlCdashigProductScenarios.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

XmlCdashigProductScenarios::XmlCdashigProductScenarios()
{
    m_SelfIsSet = false;
}

XmlCdashigProductScenarios::~XmlCdashigProductScenarios()
{
}

void XmlCdashigProductScenarios::validate()
{
    // TODO: implement validation
}

web::json::value XmlCdashigProductScenarios::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_SelfIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("self"))] = ModelBase::toJson(m_Self);
    }

    return val;
}

bool XmlCdashigProductScenarios::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("self"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("self")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<CdashigProductScenarios> refVal_setSelf;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSelf);
            setSelf(refVal_setSelf);
            
        }
    }
    return ok;
}

void XmlCdashigProductScenarios::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_SelfIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("self")), m_Self));
    }
}

bool XmlCdashigProductScenarios::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("self"))))
    {
        std::shared_ptr<CdashigProductScenarios> refVal_setSelf;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("self"))), refVal_setSelf );
        setSelf(refVal_setSelf);
    }
    return ok;
}


std::shared_ptr<CdashigProductScenarios> XmlCdashigProductScenarios::getSelf() const
{
    return m_Self;
}


void XmlCdashigProductScenarios::setSelf(const std::shared_ptr<CdashigProductScenarios>& value)
{
    m_Self = value;
    m_SelfIsSet = true;
}

bool XmlCdashigProductScenarios::selfIsSet() const
{
    return m_SelfIsSet;
}

void XmlCdashigProductScenarios::unsetSelf()
{
    m_SelfIsSet = false;
}

}
}
}
}


