/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class CdashigClassLinks (
  self: Option[CdashigClassRef] = None,
  modelClass: Option[CdashClassRef] = None,
  parentProduct: Option[CdashigProductRef] = None,
  parentClass: Option[CdashigClassRef] = None,
  subclasses: Option[Seq[CdashigClassRefSubclass]] = None,
  priorVersion: Option[CdashigClassRef] = None
) extends ApiModel

