/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CdashigDomainRef from './CdashigDomainRef';
import CdashigProductRef from './CdashigProductRef';
import CdashigScenarioFieldRef from './CdashigScenarioFieldRef';
import CdashigScenarioRef from './CdashigScenarioRef';
import RootCdashigScenarioFieldRef from './RootCdashigScenarioFieldRef';
import RootCtCodelistRefElement from './RootCtCodelistRefElement';
import SdtmigDatasetVariableRefTarget from './SdtmigDatasetVariableRefTarget';

/**
 * The CdashigScenarioFieldLinks model module.
 * @module model/CdashigScenarioFieldLinks
 * @version 1.1.0
 */
class CdashigScenarioFieldLinks {
    /**
     * Constructs a new <code>CdashigScenarioFieldLinks</code>.
     * @alias module:model/CdashigScenarioFieldLinks
     */
    constructor() { 
        
        CdashigScenarioFieldLinks.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CdashigScenarioFieldLinks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CdashigScenarioFieldLinks} obj Optional instance to populate.
     * @return {module:model/CdashigScenarioFieldLinks} The populated <code>CdashigScenarioFieldLinks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CdashigScenarioFieldLinks();

            if (data.hasOwnProperty('self')) {
                obj['self'] = CdashigScenarioFieldRef.constructFromObject(data['self']);
            }
            if (data.hasOwnProperty('codelist')) {
                obj['codelist'] = ApiClient.convertToType(data['codelist'], [RootCtCodelistRefElement]);
            }
            if (data.hasOwnProperty('parentProduct')) {
                obj['parentProduct'] = CdashigProductRef.constructFromObject(data['parentProduct']);
            }
            if (data.hasOwnProperty('parentDomain')) {
                obj['parentDomain'] = CdashigDomainRef.constructFromObject(data['parentDomain']);
            }
            if (data.hasOwnProperty('parentScenario')) {
                obj['parentScenario'] = CdashigScenarioRef.constructFromObject(data['parentScenario']);
            }
            if (data.hasOwnProperty('rootItem')) {
                obj['rootItem'] = RootCdashigScenarioFieldRef.constructFromObject(data['rootItem']);
            }
            if (data.hasOwnProperty('priorVersion')) {
                obj['priorVersion'] = CdashigScenarioFieldRef.constructFromObject(data['priorVersion']);
            }
            if (data.hasOwnProperty('sdtmigDatasetMappingTargets')) {
                obj['sdtmigDatasetMappingTargets'] = ApiClient.convertToType(data['sdtmigDatasetMappingTargets'], [SdtmigDatasetVariableRefTarget]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CdashigScenarioFieldLinks</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CdashigScenarioFieldLinks</code>.
     */
    static validateJSON(data) {
        // validate the optional field `self`
        if (data['self']) { // data not null
          CdashigScenarioFieldRef.validateJSON(data['self']);
        }
        if (data['codelist']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['codelist'])) {
                throw new Error("Expected the field `codelist` to be an array in the JSON data but got " + data['codelist']);
            }
            // validate the optional field `codelist` (array)
            for (const item of data['codelist']) {
                RootCtCodelistRefElement.validateJSON(item);
            };
        }
        // validate the optional field `parentProduct`
        if (data['parentProduct']) { // data not null
          CdashigProductRef.validateJSON(data['parentProduct']);
        }
        // validate the optional field `parentDomain`
        if (data['parentDomain']) { // data not null
          CdashigDomainRef.validateJSON(data['parentDomain']);
        }
        // validate the optional field `parentScenario`
        if (data['parentScenario']) { // data not null
          CdashigScenarioRef.validateJSON(data['parentScenario']);
        }
        // validate the optional field `rootItem`
        if (data['rootItem']) { // data not null
          RootCdashigScenarioFieldRef.validateJSON(data['rootItem']);
        }
        // validate the optional field `priorVersion`
        if (data['priorVersion']) { // data not null
          CdashigScenarioFieldRef.validateJSON(data['priorVersion']);
        }
        if (data['sdtmigDatasetMappingTargets']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['sdtmigDatasetMappingTargets'])) {
                throw new Error("Expected the field `sdtmigDatasetMappingTargets` to be an array in the JSON data but got " + data['sdtmigDatasetMappingTargets']);
            }
            // validate the optional field `sdtmigDatasetMappingTargets` (array)
            for (const item of data['sdtmigDatasetMappingTargets']) {
                SdtmigDatasetVariableRefTarget.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/CdashigScenarioFieldRef} self
 */
CdashigScenarioFieldLinks.prototype['self'] = undefined;

/**
 * @member {Array.<module:model/RootCtCodelistRefElement>} codelist
 */
CdashigScenarioFieldLinks.prototype['codelist'] = undefined;

/**
 * @member {module:model/CdashigProductRef} parentProduct
 */
CdashigScenarioFieldLinks.prototype['parentProduct'] = undefined;

/**
 * @member {module:model/CdashigDomainRef} parentDomain
 */
CdashigScenarioFieldLinks.prototype['parentDomain'] = undefined;

/**
 * @member {module:model/CdashigScenarioRef} parentScenario
 */
CdashigScenarioFieldLinks.prototype['parentScenario'] = undefined;

/**
 * @member {module:model/RootCdashigScenarioFieldRef} rootItem
 */
CdashigScenarioFieldLinks.prototype['rootItem'] = undefined;

/**
 * @member {module:model/CdashigScenarioFieldRef} priorVersion
 */
CdashigScenarioFieldLinks.prototype['priorVersion'] = undefined;

/**
 * @member {Array.<module:model/SdtmigDatasetVariableRefTarget>} sdtmigDatasetMappingTargets
 */
CdashigScenarioFieldLinks.prototype['sdtmigDatasetMappingTargets'] = undefined;






export default CdashigScenarioFieldLinks;

