/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DefaultSearchScopes from './DefaultSearchScopes';

/**
 * The MdrSearchScopesGet200Response model module.
 * @module model/MdrSearchScopesGet200Response
 * @version 1.1.0
 */
class MdrSearchScopesGet200Response {
    /**
     * Constructs a new <code>MdrSearchScopesGet200Response</code>.
     * @alias module:model/MdrSearchScopesGet200Response
     */
    constructor() { 
        
        MdrSearchScopesGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MdrSearchScopesGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MdrSearchScopesGet200Response} obj Optional instance to populate.
     * @return {module:model/MdrSearchScopesGet200Response} The populated <code>MdrSearchScopesGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MdrSearchScopesGet200Response();

            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], [DefaultSearchScopes]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MdrSearchScopesGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MdrSearchScopesGet200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['scopes'])) {
            throw new Error("Expected the field `scopes` to be an array in the JSON data but got " + data['scopes']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/DefaultSearchScopes>} scopes
 */
MdrSearchScopesGet200Response.prototype['scopes'] = undefined;






export default MdrSearchScopesGet200Response;

