/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RootCtCodelistLinks from './RootCtCodelistLinks';

/**
 * The RootCtCodelist model module.
 * @module model/RootCtCodelist
 * @version 1.1.0
 */
class RootCtCodelist {
    /**
     * Constructs a new <code>RootCtCodelist</code>.
     * @alias module:model/RootCtCodelist
     */
    constructor() { 
        
        RootCtCodelist.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RootCtCodelist</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RootCtCodelist} obj Optional instance to populate.
     * @return {module:model/RootCtCodelist} The populated <code>RootCtCodelist</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RootCtCodelist();

            if (data.hasOwnProperty('_links')) {
                obj['_links'] = RootCtCodelistLinks.constructFromObject(data['_links']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RootCtCodelist</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RootCtCodelist</code>.
     */
    static validateJSON(data) {
        // validate the optional field `_links`
        if (data['_links']) { // data not null
          RootCtCodelistLinks.validateJSON(data['_links']);
        }

        return true;
    }


}



/**
 * @member {module:model/RootCtCodelistLinks} _links
 */
RootCtCodelist.prototype['_links'] = undefined;






export default RootCtCodelist;

