//
// CdashProductLinks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CdashProductLinks: Codable {
    public var _self: CdashProductRef?
    public var priorVersion: CdashProductRef?

    public init(_self: CdashProductRef? = nil, priorVersion: CdashProductRef? = nil) {
        self._self = _self
        self.priorVersion = priorVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _self = "self"
        case priorVersion
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        _self = try container.decodeIfPresent(CdashProductRef.self, forKey: ._self)
        priorVersion = try container.decodeIfPresent(CdashProductRef.self, forKey: .priorVersion)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_self, forKey: ._self)
        try container.encodeIfPresent(priorVersion, forKey: .priorVersion)
    }
}
