//
// RootSdtmClassVariableLinks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RootSdtmClassVariableLinks: Codable {
    public var _self: RootSdtmClassVariableRef?
    public var versions: [SdtmClassVariableRefVersion]?

    public init(_self: RootSdtmClassVariableRef? = nil, versions: [SdtmClassVariableRefVersion]? = nil) {
        self._self = _self
        self.versions = versions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _self = "self"
        case versions
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        _self = try container.decodeIfPresent(RootSdtmClassVariableRef.self, forKey: ._self)
        versions = try container.decodeIfPresent([SdtmClassVariableRefVersion].self, forKey: .versions)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_self, forKey: ._self)
        try container.encodeIfPresent(versions, forKey: .versions)
    }
}
