# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RootSdtmClassVariable")

model_instance <- RootSdtmClassVariable$new()

test_that("_links", {
  # tests for the property `_links` (RootSdtmClassVariableLinks)

  # uncomment below to test the property
  #expect_equal(model.instance$`_links`, "EXPECTED_RESULT")
})
