# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CdashDomainFieldsLinks")

model_instance <- CdashDomainFieldsLinks$new()

test_that("item_self", {
  # tests for the property `item_self` (CdashDomainFieldsRef)

  # uncomment below to test the property
  #expect_equal(model.instance$`item_self`, "EXPECTED_RESULT")
})

test_that("parentProduct", {
  # tests for the property `parentProduct` (CdashProductRef)

  # uncomment below to test the property
  #expect_equal(model.instance$`parentProduct`, "EXPECTED_RESULT")
})

test_that("parentClass", {
  # tests for the property `parentClass` (CdashClassRef)

  # uncomment below to test the property
  #expect_equal(model.instance$`parentClass`, "EXPECTED_RESULT")
})

test_that("fields", {
  # tests for the property `fields` (array[CdashDomainFieldRefElement])

  # uncomment below to test the property
  #expect_equal(model.instance$`fields`, "EXPECTED_RESULT")
})
