/*
 * default_search_scopes.h
 *
 * 
 */

#ifndef _default_search_scopes_H_
#define _default_search_scopes_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct default_search_scopes_t default_search_scopes_t;


// Enum  for default_search_scopes

typedef enum { cdisc_library_api_default_search_scopes__NULL = 0, cdisc_library_api_default_search_scopes___class, cdisc_library_api_default_search_scopes__codelist, cdisc_library_api_default_search_scopes__conceptId, cdisc_library_api_default_search_scopes__core, cdisc_library_api_default_search_scopes__dataStructure, cdisc_library_api_default_search_scopes__datasetStructure, cdisc_library_api_default_search_scopes__definition, cdisc_library_api_default_search_scopes__description, cdisc_library_api_default_search_scopes__domain, cdisc_library_api_default_search_scopes__effectiveDate, cdisc_library_api_default_search_scopes__extensible, cdisc_library_api_default_search_scopes__href, cdisc_library_api_default_search_scopes__label, cdisc_library_api_default_search_scopes__measureType, cdisc_library_api_default_search_scopes__name, cdisc_library_api_default_search_scopes__preferredTerm, cdisc_library_api_default_search_scopes__product, cdisc_library_api_default_search_scopes__productGroup, cdisc_library_api_default_search_scopes__registrationStatus, cdisc_library_api_default_search_scopes__roleDescription, cdisc_library_api_default_search_scopes__sdtmTarget, cdisc_library_api_default_search_scopes__simpleDatatype, cdisc_library_api_default_search_scopes__submissionValue, cdisc_library_api_default_search_scopes__synonyms, cdisc_library_api_default_search_scopes__type, cdisc_library_api_default_search_scopes__uiHref, cdisc_library_api_default_search_scopes__valueDomain, cdisc_library_api_default_search_scopes__variableSet, cdisc_library_api_default_search_scopes__version } cdisc_library_api_default_search_scopes__e;

char* default_search_scopes_default_search_scopes_ToString(cdisc_library_api_default_search_scopes__e default_search_scopes);

cdisc_library_api_default_search_scopes__e default_search_scopes_default_search_scopes_FromString(char* default_search_scopes);

cJSON *default_search_scopes_convertToJSON(cdisc_library_api_default_search_scopes__e default_search_scopes);

cdisc_library_api_default_search_scopes__e default_search_scopes_parseFromJSON(cJSON *default_search_scopesJSON);

#endif /* _default_search_scopes_H_ */

