// tslint:disable
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CdashDomainFieldLinks,
    CdashDomainFieldLinksFromJSON,
    CdashDomainFieldLinksToJSON,
} from './';

/**
 * 
 * @export
 * @interface CdashDomainField
 */
export interface CdashDomainField  {
    /**
     * 
     * @type {string}
     * @memberof CdashDomainField
     */
    ordinal?: string;
    /**
     * 
     * @type {string}
     * @memberof CdashDomainField
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CdashDomainField
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof CdashDomainField
     */
    definition?: string;
    /**
     * 
     * @type {string}
     * @memberof CdashDomainField
     */
    domainSpecific?: string;
    /**
     * 
     * @type {string}
     * @memberof CdashDomainField
     */
    questionText?: string;
    /**
     * 
     * @type {string}
     * @memberof CdashDomainField
     */
    prompt?: string;
    /**
     * 
     * @type {string}
     * @memberof CdashDomainField
     */
    simpleDatatype?: string;
    /**
     * 
     * @type {string}
     * @memberof CdashDomainField
     */
    implementationNotes?: string;
    /**
     * 
     * @type {string}
     * @memberof CdashDomainField
     */
    mappingInstructions?: string;
    /**
     * 
     * @type {CdashDomainFieldLinks}
     * @memberof CdashDomainField
     */
    links?: CdashDomainFieldLinks;
}

export function CdashDomainFieldFromJSON(json: any): CdashDomainField {
    return {
        'ordinal': !exists(json, 'ordinal') ? undefined : json['ordinal'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'definition': !exists(json, 'definition') ? undefined : json['definition'],
        'domainSpecific': !exists(json, 'domainSpecific') ? undefined : json['domainSpecific'],
        'questionText': !exists(json, 'questionText') ? undefined : json['questionText'],
        'prompt': !exists(json, 'prompt') ? undefined : json['prompt'],
        'simpleDatatype': !exists(json, 'simpleDatatype') ? undefined : json['simpleDatatype'],
        'implementationNotes': !exists(json, 'implementationNotes') ? undefined : json['implementationNotes'],
        'mappingInstructions': !exists(json, 'mappingInstructions') ? undefined : json['mappingInstructions'],
        'links': !exists(json, '_links') ? undefined : CdashDomainFieldLinksFromJSON(json['_links']),
    };
}

export function CdashDomainFieldToJSON(value?: CdashDomainField): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'ordinal': value.ordinal,
        'name': value.name,
        'label': value.label,
        'definition': value.definition,
        'domainSpecific': value.domainSpecific,
        'questionText': value.questionText,
        'prompt': value.prompt,
        'simpleDatatype': value.simpleDatatype,
        'implementationNotes': value.implementationNotes,
        'mappingInstructions': value.mappingInstructions,
        '_links': CdashDomainFieldLinksToJSON(value.links),
    };
}


