// tslint:disable
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CtPackageRef,
    CtPackageRefFromJSON,
    CtPackageRefToJSON,
} from './';

/**
 * 
 * @export
 * @interface CtPackageLinks
 */
export interface CtPackageLinks  {
    /**
     * 
     * @type {CtPackageRef}
     * @memberof CtPackageLinks
     */
    self?: CtPackageRef;
    /**
     * 
     * @type {CtPackageRef}
     * @memberof CtPackageLinks
     */
    priorVersion?: CtPackageRef;
}

export function CtPackageLinksFromJSON(json: any): CtPackageLinks {
    return {
        'self': !exists(json, 'self') ? undefined : CtPackageRefFromJSON(json['self']),
        'priorVersion': !exists(json, 'priorVersion') ? undefined : CtPackageRefFromJSON(json['priorVersion']),
    };
}

export function CtPackageLinksToJSON(value?: CtPackageLinks): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'self': CtPackageRefToJSON(value.self),
        'priorVersion': CtPackageRefToJSON(value.priorVersion),
    };
}


