(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
      ordinal: string
          
           option [@default None]
        
        ; [@key "ordinal"]
      name: string
          
           option [@default None]
        
        ; [@key "name"]
      label: string
          
           option [@default None]
        
        ; [@key "label"]
      description: string
          
           option [@default None]
        
        ; [@key "description"]
      _links: Cdashig_class_links.t
          
           option [@default None]
        
        ; [@key "_links"]
      domains: Cdashig_domain.t list
         [@default []]
        ; [@key "domains"]
      scenarios: Cdashig_scenario.t list
         [@default []]
        ; [@key "scenarios"]
} [@@deriving yojson { strict = false }, show, eq ];;

let create () : t = {
    ordinal = None;
    name = None;
    label = None;
    description = None;
    _links = None;
    domains = [];
    scenarios = [];
}

