/** CDISC Library API
  * REST API Documentation for CDISC Library in production server
  *
  * The version of the OpenAPI document: 1.1.0
  * Contact: cdisc_library_support@cdisc.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package org.openapitools.client.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** 
  * @param self 
  * @param parentProduct 
  * @param priorVersion 
  */
case class AdamDatastructureLinks(
    self: Option[AdamDatastructureRef] = None,
    parentProduct: Option[AdamProductRef] = None,
    priorVersion: Option[AdamDatastructureRef] = None
)
  
object AdamDatastructureLinks {
  given encoderAdamDatastructureLinks: Encoder[AdamDatastructureLinks] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.self.map(v => "self" -> v.asJson),
        t.parentProduct.map(v => "parentProduct" -> v.asJson),
        t.priorVersion.map(v => "priorVersion" -> v.asJson)
      ).flatten
    }
  }
  given decoderAdamDatastructureLinks: Decoder[AdamDatastructureLinks] = Decoder.instance { c =>
    for {
      self <- c.downField("self").as[Option[AdamDatastructureRef]]
      parentProduct <- c.downField("parentProduct").as[Option[AdamProductRef]]
      priorVersion <- c.downField("priorVersion").as[Option[AdamDatastructureRef]]
    } yield AdamDatastructureLinks(
      self = self,
      parentProduct = parentProduct,
      priorVersion = priorVersion
    )
  }
}

