/** CDISC Library API
  * REST API Documentation for CDISC Library in production server
  *
  * The version of the OpenAPI document: 1.1.0
  * Contact: cdisc_library_support@cdisc.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package org.openapitools.client.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}

import scala.collection.immutable.Seq

/** 
  * @param self 
  * @param responsegroups 
  */
case class QrsResponsegroupsLinks(
    self: Option[QrsResponsegroupsRef] = None,
    responsegroups: Option[Seq[QrsResponsegroupRefElement]] = None
)
  
object QrsResponsegroupsLinks {
  given encoderQrsResponsegroupsLinks: Encoder[QrsResponsegroupsLinks] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.self.map(v => "self" -> v.asJson),
        t.responsegroups.map(v => "responsegroups" -> v.asJson)
      ).flatten
    }
  }
  given decoderQrsResponsegroupsLinks: Decoder[QrsResponsegroupsLinks] = Decoder.instance { c =>
    for {
      self <- c.downField("self").as[Option[QrsResponsegroupsRef]]
      responsegroups <- c.downField("responsegroups").as[Option[Seq[QrsResponsegroupRefElement]]]
    } yield QrsResponsegroupsLinks(
      self = self,
      responsegroups = responsegroups
    )
  }
}

