/*
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CdashigClassRef;
import org.openapitools.client.model.CdashigDomainRef;
import org.openapitools.client.model.CdashigProductRef;
import org.openapitools.client.model.CdashigScenarioFieldRefElement;
import org.openapitools.client.model.CdashigScenarioFieldsRef;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CdashigScenarioFieldsLinks
 */
public class CdashigScenarioFieldsLinksTest {
    private final CdashigScenarioFieldsLinks model = new CdashigScenarioFieldsLinks();

    /**
     * Model tests for CdashigScenarioFieldsLinks
     */
    @Test
    public void testCdashigScenarioFieldsLinks() {
        // TODO: test CdashigScenarioFieldsLinks
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

    /**
     * Test the property 'parentProduct'
     */
    @Test
    public void parentProductTest() {
        // TODO: test parentProduct
    }

    /**
     * Test the property 'parentClass'
     */
    @Test
    public void parentClassTest() {
        // TODO: test parentClass
    }

    /**
     * Test the property 'parentDomain'
     */
    @Test
    public void parentDomainTest() {
        // TODO: test parentDomain
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

}
