/*
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ExportSdtmClassVariablesRow;
import org.openapitools.client.model.ExportSdtmDatasetVariablesRow;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ExportSdtmVariablesTable
 */
public class ExportSdtmVariablesTableTest {
    private final ExportSdtmVariablesTable model = new ExportSdtmVariablesTable();

    /**
     * Model tests for ExportSdtmVariablesTable
     */
    @Test
    public void testExportSdtmVariablesTable() {
        // TODO: test ExportSdtmVariablesTable
    }

    /**
     * Test the property 'classVariables'
     */
    @Test
    public void classVariablesTest() {
        // TODO: test classVariables
    }

    /**
     * Test the property 'datasetVariables'
     */
    @Test
    public void datasetVariablesTest() {
        // TODO: test datasetVariables
    }

}
