// tslint:disable
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CdashClassRefElement
 */
export interface CdashClassRefElement {
    /**
     * @type {string}
     * @memberof CdashClassRefElement
     */
    href?: string;
    /**
     * @type {string}
     * @memberof CdashClassRefElement
     */
    title?: string;
    /**
     * @type {string}
     * @memberof CdashClassRefElement
     */
    type?: string;
}
