/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CdashClassLinks
import org.openapitools.client.models.CdashClassRef
import org.openapitools.client.models.CdashProductRef

class CdashClassLinksTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CdashClassLinks
        //val modelInstance = CdashClassLinks()

        // to test the property `self`
        should("test self") {
            // uncomment below to test the property
            //modelInstance.self shouldBe ("TODO")
        }

        // to test the property `parentProduct`
        should("test parentProduct") {
            // uncomment below to test the property
            //modelInstance.parentProduct shouldBe ("TODO")
        }

        // to test the property `priorVersion`
        should("test priorVersion") {
            // uncomment below to test the property
            //modelInstance.priorVersion shouldBe ("TODO")
        }

    }
}
