# coding: utf-8

"""
    CDISC Library API

    REST API Documentation for CDISC Library in production server

    The version of the OpenAPI document: 1.1.0
    Contact: cdisc_library_support@cdisc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.export_cdash_domain_variables_row import ExportCdashDomainVariablesRow  # noqa: E501

class TestExportCdashDomainVariablesRow(unittest.TestCase):
    """ExportCdashDomainVariablesRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExportCdashDomainVariablesRow:
        """Test ExportCdashDomainVariablesRow
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExportCdashDomainVariablesRow`
        """
        model = ExportCdashDomainVariablesRow()  # noqa: E501
        if include_optional:
            return ExportCdashDomainVariablesRow(
                version = '',
                var_class = '',
                domain = '',
                variable_order = '',
                cdash_variable = '',
                cdash_variable_label = '',
                draft_cdash_definition = '',
                domain_specific = '',
                question_text = '',
                prompt = '',
                type = '',
                sdtm_target = [
                    ''
                    ],
                mapping_instructions = '',
                controlled_terminology_codelist_name = '',
                implementation_notes = ''
            )
        else:
            return ExportCdashDomainVariablesRow(
        )
        """

    def testExportCdashDomainVariablesRow(self):
        """Test ExportCdashDomainVariablesRow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
