# coding: utf-8

"""
    CDISC Library API

    REST API Documentation for CDISC Library in production server

    The version of the OpenAPI document: 1.1.0
    Contact: cdisc_library_support@cdisc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.sendig_product import SendigProduct  # noqa: E501

class TestSendigProduct(unittest.TestCase):
    """SendigProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendigProduct:
        """Test SendigProduct
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendigProduct`
        """
        model = SendigProduct()  # noqa: E501
        if include_optional:
            return SendigProduct(
                name = 'SENDIG v3.1',
                label = 'Standard for Exchange ofâ€¦ies Version 3.1 (Final)',
                description = 'The SENDIG is intended to guide the organization, structure, and format of standard nonclinical tabulation datasets for interchange between organizations such as sponsors and CROs, and for submission to regulatory authorities such as the U.S. Food and Drug Administration (FDA).',
                source = 'Prepared by the CDISC Stâ€¦f Nonclinical Data Team',
                effective_date = '2016-06-27',
                registration_status = 'Final',
                version = '3.1',
                links = openapi_client.models.sendig_product_links.SendigProductLinks(
                    self = openapi_client.models.sendig_product_ref.SendigProductRef(
                        href = '/mdr/sendig/3-1', 
                        title = 'Standard for Exchange of Nonclinical Data Implementation Guide: Nonclinical Studies Version 3.1 (Final)', 
                        type = 'Implementation Guide', ), 
                    model = openapi_client.models.sdtm_product_ref.SdtmProductRef(
                        href = '/mdr/sdtm/1-8', 
                        title = 'Study Data Tabulation Model Version 1.8 (Final)', 
                        type = 'Foundational Model', ), 
                    prior_version = openapi_client.models.sendig_product_ref.SendigProductRef(
                        href = '/mdr/sendig/3-1', 
                        title = 'Standard for Exchange of Nonclinical Data Implementation Guide: Nonclinical Studies Version 3.1 (Final)', 
                        type = 'Implementation Guide', ), ),
                classes = [
                    openapi_client.models.sendig_class.SendigClass(
                        ordinal = '5', 
                        name = 'Findings', 
                        label = 'Findings Observation Class', 
                        description = 'This SDTM class captures the observations resulting from planned evaluations to address specific tests or questions such as laboratory tests, ECG testing, and questions listed on questionnaires. (Source: CDISC Controlled Terminology, GNRLOBSC, C103373, 2018-06-29)', 
                        _links = openapi_client.models.sendig_class_links.SendigClassLinks(
                            self = openapi_client.models.sendig_class_ref.SendigClassRef(
                                href = '/mdr/sendig/3-1/classes/Findings', 
                                title = 'Findings Observation Class', 
                                type = 'Class', ), 
                            model_class = openapi_client.models.sdtm_class_ref.SdtmClassRef(
                                href = '/mdr/sdtm/1-8/classes/Findings', 
                                title = 'Findings Observation Class', 
                                type = 'Class', ), 
                            parent_product = openapi_client.models.sendig_product_ref.SendigProductRef(
                                href = '/mdr/sendig/3-1', 
                                title = 'Standard for Exchange of Nonclinical Data Implementation Guide: Nonclinical Studies Version 3.1 (Final)', 
                                type = 'Implementation Guide', ), 
                            parent_class = openapi_client.models.sendig_class_ref.SendigClassRef(
                                href = '/mdr/sendig/3-1/classes/Findings', 
                                title = 'Findings Observation Class', 
                                type = 'Class', ), 
                            subclasses = [
                                openapi_client.models.sendig_class_ref_subclass.SendigClassRefSubclass(
                                    href = '/mdr/sendig/3-1/classes/FindingsAbout', 
                                    title = 'Findings About Observation Class', 
                                    type = 'Class', )
                                ], 
                            prior_version = , ), 
                        datasets = [
                            openapi_client.models.sendig_dataset.SendigDataset(
                                ordinal = '20', 
                                name = 'VS', 
                                label = 'Vital Signs', 
                                description = 'A findings domain that contains measurements including but not limited to blood pressure, temperature, respiration, body surface area, body mass index, height and weight. (Source: CDISC Controlled Terminology, SDOMAIN, C49622, 2018-06-29)', 
                                dataset_structure = 'One record per measurement per observation time per subject', 
                                dataset_variables = [
                                    openapi_client.models.sendig_dataset_variable.SendigDatasetVariable(
                                        ordinal = '8', 
                                        name = 'VSTEST', 
                                        label = 'Vital Signs Test Name', 
                                        description = 'Long name for VSTESTCD. The value in VSTEST cannot be longer than 40 characters.', 
                                        role = 'Synonym Qualifier', 
                                        simple_datatype = 'Char', 
                                        core = 'Req', 
                                        described_value_domain = 'Value domain example', 
                                        value_list = ["Value example 1","Value example 2"], )
                                    ], )
                            ], )
                    ]
            )
        else:
            return SendigProduct(
        )
        """

    def testSendigProduct(self):
        """Test SendigProduct"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
