# coding: utf-8

"""
    CDISC Library API

    REST API Documentation for CDISC Library in production server

    The version of the OpenAPI document: 1.1.0
    Contact: cdisc_library_support@cdisc.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.export_adam_variables_table import ExportAdamVariablesTable  # noqa: E501

class TestExportAdamVariablesTable(unittest.TestCase):
    """ExportAdamVariablesTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExportAdamVariablesTable:
        """Test ExportAdamVariablesTable
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExportAdamVariablesTable`
        """
        model = ExportAdamVariablesTable()  # noqa: E501
        if include_optional:
            return ExportAdamVariablesTable(
                variables = [
                    openapi_client.models.export_adam_variables_row.ExportAdamVariablesRow(
                        version = '', 
                        data_structure_name = '', 
                        dataset_name = '', 
                        variable_group = '', 
                        variable_name = '', 
                        variable_label = '', 
                        type = '', 
                        codelist/controlled_terms = '', 
                        core = '', 
                        cdisc_notes = '', )
                    ]
            )
        else:
            return ExportAdamVariablesTable(
        )
        """

    def testExportAdamVariablesTable(self):
        """Test ExportAdamVariablesTable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
