/* tslint:disable */
/* eslint-disable */
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdamVarsetRefElement } from './AdamVarsetRefElement';
import {
    AdamVarsetRefElementFromJSON,
    AdamVarsetRefElementFromJSONTyped,
    AdamVarsetRefElementToJSON,
    AdamVarsetRefElementToJSONTyped,
} from './AdamVarsetRefElement';
import type { AdamDatastructureVarsetsRef } from './AdamDatastructureVarsetsRef';
import {
    AdamDatastructureVarsetsRefFromJSON,
    AdamDatastructureVarsetsRefFromJSONTyped,
    AdamDatastructureVarsetsRefToJSON,
    AdamDatastructureVarsetsRefToJSONTyped,
} from './AdamDatastructureVarsetsRef';
import type { AdamProductRef } from './AdamProductRef';
import {
    AdamProductRefFromJSON,
    AdamProductRefFromJSONTyped,
    AdamProductRefToJSON,
    AdamProductRefToJSONTyped,
} from './AdamProductRef';

/**
 * 
 * @export
 * @interface AdamDatastructureVarsetsLinks
 */
export interface AdamDatastructureVarsetsLinks {
    /**
     * 
     * @type {AdamDatastructureVarsetsRef}
     * @memberof AdamDatastructureVarsetsLinks
     */
    self?: AdamDatastructureVarsetsRef;
    /**
     * 
     * @type {AdamProductRef}
     * @memberof AdamDatastructureVarsetsLinks
     */
    parentProduct?: AdamProductRef;
    /**
     * 
     * @type {AdamDatastructureVarsetsRef}
     * @memberof AdamDatastructureVarsetsLinks
     */
    priorVersion?: AdamDatastructureVarsetsRef;
    /**
     * 
     * @type {Array<AdamVarsetRefElement>}
     * @memberof AdamDatastructureVarsetsLinks
     */
    analysisVariableSets?: Array<AdamVarsetRefElement>;
}

/**
 * Check if a given object implements the AdamDatastructureVarsetsLinks interface.
 */
export function instanceOfAdamDatastructureVarsetsLinks(value: object): value is AdamDatastructureVarsetsLinks {
    return true;
}

export function AdamDatastructureVarsetsLinksFromJSON(json: any): AdamDatastructureVarsetsLinks {
    return AdamDatastructureVarsetsLinksFromJSONTyped(json, false);
}

export function AdamDatastructureVarsetsLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdamDatastructureVarsetsLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'self': json['self'] == null ? undefined : AdamDatastructureVarsetsRefFromJSON(json['self']),
        'parentProduct': json['parentProduct'] == null ? undefined : AdamProductRefFromJSON(json['parentProduct']),
        'priorVersion': json['priorVersion'] == null ? undefined : AdamDatastructureVarsetsRefFromJSON(json['priorVersion']),
        'analysisVariableSets': json['analysisVariableSets'] == null ? undefined : ((json['analysisVariableSets'] as Array<any>).map(AdamVarsetRefElementFromJSON)),
    };
}

export function AdamDatastructureVarsetsLinksToJSON(json: any): AdamDatastructureVarsetsLinks {
    return AdamDatastructureVarsetsLinksToJSONTyped(json, false);
}

export function AdamDatastructureVarsetsLinksToJSONTyped(value?: AdamDatastructureVarsetsLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'self': AdamDatastructureVarsetsRefToJSON(value['self']),
        'parentProduct': AdamProductRefToJSON(value['parentProduct']),
        'priorVersion': AdamDatastructureVarsetsRefToJSON(value['priorVersion']),
        'analysisVariableSets': value['analysisVariableSets'] == null ? undefined : ((value['analysisVariableSets'] as Array<any>).map(AdamVarsetRefElementToJSON)),
    };
}

