/* tslint:disable */
/* eslint-disable */
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RootCdashigScenarioFieldLinks } from './RootCdashigScenarioFieldLinks';
import {
    RootCdashigScenarioFieldLinksFromJSON,
    RootCdashigScenarioFieldLinksFromJSONTyped,
    RootCdashigScenarioFieldLinksToJSON,
    RootCdashigScenarioFieldLinksToJSONTyped,
} from './RootCdashigScenarioFieldLinks';

/**
 * 
 * @export
 * @interface RootCdashigScenarioField
 */
export interface RootCdashigScenarioField {
    /**
     * 
     * @type {RootCdashigScenarioFieldLinks}
     * @memberof RootCdashigScenarioField
     */
    links?: RootCdashigScenarioFieldLinks;
}

/**
 * Check if a given object implements the RootCdashigScenarioField interface.
 */
export function instanceOfRootCdashigScenarioField(value: object): value is RootCdashigScenarioField {
    return true;
}

export function RootCdashigScenarioFieldFromJSON(json: any): RootCdashigScenarioField {
    return RootCdashigScenarioFieldFromJSONTyped(json, false);
}

export function RootCdashigScenarioFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): RootCdashigScenarioField {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['_links'] == null ? undefined : RootCdashigScenarioFieldLinksFromJSON(json['_links']),
    };
}

export function RootCdashigScenarioFieldToJSON(json: any): RootCdashigScenarioField {
    return RootCdashigScenarioFieldToJSONTyped(json, false);
}

export function RootCdashigScenarioFieldToJSONTyped(value?: RootCdashigScenarioField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_links': RootCdashigScenarioFieldLinksToJSON(value['links']),
    };
}

