/* tslint:disable */
/* eslint-disable */
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SdtmClassRefSubclass } from './SdtmClassRefSubclass';
import {
    SdtmClassRefSubclassFromJSON,
    SdtmClassRefSubclassFromJSONTyped,
    SdtmClassRefSubclassToJSON,
    SdtmClassRefSubclassToJSONTyped,
} from './SdtmClassRefSubclass';
import type { SdtmProductRef } from './SdtmProductRef';
import {
    SdtmProductRefFromJSON,
    SdtmProductRefFromJSONTyped,
    SdtmProductRefToJSON,
    SdtmProductRefToJSONTyped,
} from './SdtmProductRef';
import type { SdtmClassRef } from './SdtmClassRef';
import {
    SdtmClassRefFromJSON,
    SdtmClassRefFromJSONTyped,
    SdtmClassRefToJSON,
    SdtmClassRefToJSONTyped,
} from './SdtmClassRef';

/**
 * 
 * @export
 * @interface SdtmClassLinks
 */
export interface SdtmClassLinks {
    /**
     * 
     * @type {SdtmClassRef}
     * @memberof SdtmClassLinks
     */
    self?: SdtmClassRef;
    /**
     * 
     * @type {SdtmProductRef}
     * @memberof SdtmClassLinks
     */
    parentProduct?: SdtmProductRef;
    /**
     * 
     * @type {SdtmClassRef}
     * @memberof SdtmClassLinks
     */
    parentClass?: SdtmClassRef;
    /**
     * 
     * @type {Array<SdtmClassRefSubclass>}
     * @memberof SdtmClassLinks
     */
    subclasses?: Array<SdtmClassRefSubclass>;
    /**
     * 
     * @type {SdtmClassRef}
     * @memberof SdtmClassLinks
     */
    priorVersion?: SdtmClassRef;
}

/**
 * Check if a given object implements the SdtmClassLinks interface.
 */
export function instanceOfSdtmClassLinks(value: object): value is SdtmClassLinks {
    return true;
}

export function SdtmClassLinksFromJSON(json: any): SdtmClassLinks {
    return SdtmClassLinksFromJSONTyped(json, false);
}

export function SdtmClassLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): SdtmClassLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'self': json['self'] == null ? undefined : SdtmClassRefFromJSON(json['self']),
        'parentProduct': json['parentProduct'] == null ? undefined : SdtmProductRefFromJSON(json['parentProduct']),
        'parentClass': json['parentClass'] == null ? undefined : SdtmClassRefFromJSON(json['parentClass']),
        'subclasses': json['subclasses'] == null ? undefined : ((json['subclasses'] as Array<any>).map(SdtmClassRefSubclassFromJSON)),
        'priorVersion': json['priorVersion'] == null ? undefined : SdtmClassRefFromJSON(json['priorVersion']),
    };
}

export function SdtmClassLinksToJSON(json: any): SdtmClassLinks {
    return SdtmClassLinksToJSONTyped(json, false);
}

export function SdtmClassLinksToJSONTyped(value?: SdtmClassLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'self': SdtmClassRefToJSON(value['self']),
        'parentProduct': SdtmProductRefToJSON(value['parentProduct']),
        'parentClass': SdtmClassRefToJSON(value['parentClass']),
        'subclasses': value['subclasses'] == null ? undefined : ((value['subclasses'] as Array<any>).map(SdtmClassRefSubclassToJSON)),
        'priorVersion': SdtmClassRefToJSON(value['priorVersion']),
    };
}

