/* tslint:disable */
/* eslint-disable */
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SdtmigProductRef } from './SdtmigProductRef';
import {
    SdtmigProductRefFromJSON,
    SdtmigProductRefFromJSONTyped,
    SdtmigProductRefToJSON,
    SdtmigProductRefToJSONTyped,
} from './SdtmigProductRef';
import type { SdtmClassRef } from './SdtmClassRef';
import {
    SdtmClassRefFromJSON,
    SdtmClassRefFromJSONTyped,
    SdtmClassRefToJSON,
    SdtmClassRefToJSONTyped,
} from './SdtmClassRef';
import type { SdtmigClassRef } from './SdtmigClassRef';
import {
    SdtmigClassRefFromJSON,
    SdtmigClassRefFromJSONTyped,
    SdtmigClassRefToJSON,
    SdtmigClassRefToJSONTyped,
} from './SdtmigClassRef';
import type { SdtmigClassRefSubclass } from './SdtmigClassRefSubclass';
import {
    SdtmigClassRefSubclassFromJSON,
    SdtmigClassRefSubclassFromJSONTyped,
    SdtmigClassRefSubclassToJSON,
    SdtmigClassRefSubclassToJSONTyped,
} from './SdtmigClassRefSubclass';

/**
 * 
 * @export
 * @interface SdtmigClassLinks
 */
export interface SdtmigClassLinks {
    /**
     * 
     * @type {SdtmigClassRef}
     * @memberof SdtmigClassLinks
     */
    self?: SdtmigClassRef;
    /**
     * 
     * @type {SdtmClassRef}
     * @memberof SdtmigClassLinks
     */
    modelClass?: SdtmClassRef;
    /**
     * 
     * @type {SdtmigProductRef}
     * @memberof SdtmigClassLinks
     */
    parentProduct?: SdtmigProductRef;
    /**
     * 
     * @type {SdtmigClassRef}
     * @memberof SdtmigClassLinks
     */
    parentClass?: SdtmigClassRef;
    /**
     * 
     * @type {Array<SdtmigClassRefSubclass>}
     * @memberof SdtmigClassLinks
     */
    subclasses?: Array<SdtmigClassRefSubclass>;
    /**
     * 
     * @type {SdtmigClassRef}
     * @memberof SdtmigClassLinks
     */
    priorVersion?: SdtmigClassRef;
}

/**
 * Check if a given object implements the SdtmigClassLinks interface.
 */
export function instanceOfSdtmigClassLinks(value: object): value is SdtmigClassLinks {
    return true;
}

export function SdtmigClassLinksFromJSON(json: any): SdtmigClassLinks {
    return SdtmigClassLinksFromJSONTyped(json, false);
}

export function SdtmigClassLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): SdtmigClassLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'self': json['self'] == null ? undefined : SdtmigClassRefFromJSON(json['self']),
        'modelClass': json['modelClass'] == null ? undefined : SdtmClassRefFromJSON(json['modelClass']),
        'parentProduct': json['parentProduct'] == null ? undefined : SdtmigProductRefFromJSON(json['parentProduct']),
        'parentClass': json['parentClass'] == null ? undefined : SdtmigClassRefFromJSON(json['parentClass']),
        'subclasses': json['subclasses'] == null ? undefined : ((json['subclasses'] as Array<any>).map(SdtmigClassRefSubclassFromJSON)),
        'priorVersion': json['priorVersion'] == null ? undefined : SdtmigClassRefFromJSON(json['priorVersion']),
    };
}

export function SdtmigClassLinksToJSON(json: any): SdtmigClassLinks {
    return SdtmigClassLinksToJSONTyped(json, false);
}

export function SdtmigClassLinksToJSONTyped(value?: SdtmigClassLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'self': SdtmigClassRefToJSON(value['self']),
        'modelClass': SdtmClassRefToJSON(value['modelClass']),
        'parentProduct': SdtmigProductRefToJSON(value['parentProduct']),
        'parentClass': SdtmigClassRefToJSON(value['parentClass']),
        'subclasses': value['subclasses'] == null ? undefined : ((value['subclasses'] as Array<any>).map(SdtmigClassRefSubclassToJSON)),
        'priorVersion': SdtmigClassRefToJSON(value['priorVersion']),
    };
}

