/* tslint:disable */
/* eslint-disable */
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SdtmigDatasetVariable } from './SdtmigDatasetVariable';
import {
    SdtmigDatasetVariableFromJSON,
    SdtmigDatasetVariableFromJSONTyped,
    SdtmigDatasetVariableToJSON,
    SdtmigDatasetVariableToJSONTyped,
} from './SdtmigDatasetVariable';

/**
 * 
 * @export
 * @interface XmlSdtmigDatasetVariable
 */
export interface XmlSdtmigDatasetVariable {
    /**
     * 
     * @type {SdtmigDatasetVariable}
     * @memberof XmlSdtmigDatasetVariable
     */
    self?: SdtmigDatasetVariable;
}

/**
 * Check if a given object implements the XmlSdtmigDatasetVariable interface.
 */
export function instanceOfXmlSdtmigDatasetVariable(value: object): value is XmlSdtmigDatasetVariable {
    return true;
}

export function XmlSdtmigDatasetVariableFromJSON(json: any): XmlSdtmigDatasetVariable {
    return XmlSdtmigDatasetVariableFromJSONTyped(json, false);
}

export function XmlSdtmigDatasetVariableFromJSONTyped(json: any, ignoreDiscriminator: boolean): XmlSdtmigDatasetVariable {
    if (json == null) {
        return json;
    }
    return {
        
        'self': json['self'] == null ? undefined : SdtmigDatasetVariableFromJSON(json['self']),
    };
}

export function XmlSdtmigDatasetVariableToJSON(json: any): XmlSdtmigDatasetVariable {
    return XmlSdtmigDatasetVariableToJSONTyped(json, false);
}

export function XmlSdtmigDatasetVariableToJSONTyped(value?: XmlSdtmigDatasetVariable | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'self': SdtmigDatasetVariableToJSON(value['self']),
    };
}

