/*
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AdamVariable;
import org.openapitools.client.model.AdamVarsetLinks;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * AdamVarset
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-22T20:17:16.173989497Z[Etc/UTC]", comments = "Generator version: 7.16.0-SNAPSHOT")
public class AdamVarset {
  public static final String SERIALIZED_NAME_ORDINAL = "ordinal";
  @SerializedName(SERIALIZED_NAME_ORDINAL)
  @javax.annotation.Nullable
  private String ordinal;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  @javax.annotation.Nullable
  private String label;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  @javax.annotation.Nullable
  private AdamVarsetLinks links;

  public static final String SERIALIZED_NAME_ANALYSIS_VARIABLES = "analysisVariables";
  @SerializedName(SERIALIZED_NAME_ANALYSIS_VARIABLES)
  @javax.annotation.Nullable
  private List<AdamVariable> analysisVariables = new ArrayList<>();

  public AdamVarset() {
  }

  public AdamVarset ordinal(@javax.annotation.Nullable String ordinal) {
    this.ordinal = ordinal;
    return this;
  }

  /**
   * Get ordinal
   * @return ordinal
   */
  @javax.annotation.Nullable
  public String getOrdinal() {
    return ordinal;
  }

  public void setOrdinal(@javax.annotation.Nullable String ordinal) {
    this.ordinal = ordinal;
  }


  public AdamVarset name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public AdamVarset label(@javax.annotation.Nullable String label) {
    this.label = label;
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @javax.annotation.Nullable
  public String getLabel() {
    return label;
  }

  public void setLabel(@javax.annotation.Nullable String label) {
    this.label = label;
  }


  public AdamVarset description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public AdamVarset links(@javax.annotation.Nullable AdamVarsetLinks links) {
    this.links = links;
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  public AdamVarsetLinks getLinks() {
    return links;
  }

  public void setLinks(@javax.annotation.Nullable AdamVarsetLinks links) {
    this.links = links;
  }


  public AdamVarset analysisVariables(@javax.annotation.Nullable List<AdamVariable> analysisVariables) {
    this.analysisVariables = analysisVariables;
    return this;
  }

  public AdamVarset addAnalysisVariablesItem(AdamVariable analysisVariablesItem) {
    if (this.analysisVariables == null) {
      this.analysisVariables = new ArrayList<>();
    }
    this.analysisVariables.add(analysisVariablesItem);
    return this;
  }

  /**
   * Get analysisVariables
   * @return analysisVariables
   */
  @javax.annotation.Nullable
  public List<AdamVariable> getAnalysisVariables() {
    return analysisVariables;
  }

  public void setAnalysisVariables(@javax.annotation.Nullable List<AdamVariable> analysisVariables) {
    this.analysisVariables = analysisVariables;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdamVarset adamVarset = (AdamVarset) o;
    return Objects.equals(this.ordinal, adamVarset.ordinal) &&
        Objects.equals(this.name, adamVarset.name) &&
        Objects.equals(this.label, adamVarset.label) &&
        Objects.equals(this.description, adamVarset.description) &&
        Objects.equals(this.links, adamVarset.links) &&
        Objects.equals(this.analysisVariables, adamVarset.analysisVariables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ordinal, name, label, description, links, analysisVariables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdamVarset {\n");
    sb.append("    ordinal: ").append(toIndentedString(ordinal)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    analysisVariables: ").append(toIndentedString(analysisVariables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("ordinal", "name", "label", "description", "_links", "analysisVariables"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AdamVarset
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AdamVarset.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AdamVarset is not found in the empty JSON string", AdamVarset.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AdamVarset.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AdamVarset` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("ordinal") != null && !jsonObj.get("ordinal").isJsonNull()) && !jsonObj.get("ordinal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ordinal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ordinal").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("label") != null && !jsonObj.get("label").isJsonNull()) && !jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // validate the optional field `_links`
      if (jsonObj.get("_links") != null && !jsonObj.get("_links").isJsonNull()) {
        AdamVarsetLinks.validateJsonElement(jsonObj.get("_links"));
      }
      if (jsonObj.get("analysisVariables") != null && !jsonObj.get("analysisVariables").isJsonNull()) {
        JsonArray jsonArrayanalysisVariables = jsonObj.getAsJsonArray("analysisVariables");
        if (jsonArrayanalysisVariables != null) {
          // ensure the json data is an array
          if (!jsonObj.get("analysisVariables").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `analysisVariables` to be an array in the JSON string but got `%s`", jsonObj.get("analysisVariables").toString()));
          }

          // validate the optional field `analysisVariables` (array)
          for (int i = 0; i < jsonArrayanalysisVariables.size(); i++) {
            AdamVariable.validateJsonElement(jsonArrayanalysisVariables.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdamVarset.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdamVarset' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdamVarset> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdamVarset.class));

       return (TypeAdapter<T>) new TypeAdapter<AdamVarset>() {
           @Override
           public void write(JsonWriter out, AdamVarset value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AdamVarset read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AdamVarset given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AdamVarset
   * @throws IOException if the JSON string is invalid with respect to AdamVarset
   */
  public static AdamVarset fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AdamVarset.class);
  }

  /**
   * Convert an instance of AdamVarset to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

