/*
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.AdamDatastructureRefElement;
import org.openapitools.client.model.AdamProductDatastructuresRef;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AdamProductDatastructuresLinks {
  
  @SerializedName("self")
  private AdamProductDatastructuresRef self = null;
  @SerializedName("priorVersion")
  private AdamProductDatastructuresRef priorVersion = null;
  @SerializedName("dataStructures")
  private List<AdamDatastructureRefElement> dataStructures = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public AdamProductDatastructuresRef getSelf() {
    return self;
  }
  public void setSelf(AdamProductDatastructuresRef self) {
    this.self = self;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public AdamProductDatastructuresRef getPriorVersion() {
    return priorVersion;
  }
  public void setPriorVersion(AdamProductDatastructuresRef priorVersion) {
    this.priorVersion = priorVersion;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<AdamDatastructureRefElement> getDataStructures() {
    return dataStructures;
  }
  public void setDataStructures(List<AdamDatastructureRefElement> dataStructures) {
    this.dataStructures = dataStructures;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdamProductDatastructuresLinks adamProductDatastructuresLinks = (AdamProductDatastructuresLinks) o;
    return (this.self == null ? adamProductDatastructuresLinks.self == null : this.self.equals(adamProductDatastructuresLinks.self)) &&
        (this.priorVersion == null ? adamProductDatastructuresLinks.priorVersion == null : this.priorVersion.equals(adamProductDatastructuresLinks.priorVersion)) &&
        (this.dataStructures == null ? adamProductDatastructuresLinks.dataStructures == null : this.dataStructures.equals(adamProductDatastructuresLinks.dataStructures));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.self == null ? 0: this.self.hashCode());
    result = 31 * result + (this.priorVersion == null ? 0: this.priorVersion.hashCode());
    result = 31 * result + (this.dataStructures == null ? 0: this.dataStructures.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdamProductDatastructuresLinks {\n");
    
    sb.append("  self: ").append(self).append("\n");
    sb.append("  priorVersion: ").append(priorVersion).append("\n");
    sb.append("  dataStructures: ").append(dataStructures).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
