/*
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.QrsResponsegroupRef;
import org.openapitools.client.model.QrsResponses;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class QrsResponsegroupLinks {
  
  @SerializedName("self")
  private QrsResponsegroupRef self = null;
  @SerializedName("responses")
  private List<QrsResponses> responses = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public QrsResponsegroupRef getSelf() {
    return self;
  }
  public void setSelf(QrsResponsegroupRef self) {
    this.self = self;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<QrsResponses> getResponses() {
    return responses;
  }
  public void setResponses(List<QrsResponses> responses) {
    this.responses = responses;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QrsResponsegroupLinks qrsResponsegroupLinks = (QrsResponsegroupLinks) o;
    return (this.self == null ? qrsResponsegroupLinks.self == null : this.self.equals(qrsResponsegroupLinks.self)) &&
        (this.responses == null ? qrsResponsegroupLinks.responses == null : this.responses.equals(qrsResponsegroupLinks.responses));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.self == null ? 0: this.self.hashCode());
    result = 31 * result + (this.responses == null ? 0: this.responses.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class QrsResponsegroupLinks {\n");
    
    sb.append("  self: ").append(self).append("\n");
    sb.append("  responses: ").append(responses).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
