/*
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.SdtmClassRef;
import org.openapitools.client.model.SdtmClassRefSubclass;
import org.openapitools.client.model.SdtmProductRef;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SdtmClassLinks
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-22T20:17:16.173989497Z[Etc/UTC]", comments = "Generator version: 7.16.0-SNAPSHOT")
public class SdtmClassLinks {
  public static final String SERIALIZED_NAME_SELF = "self";
  @SerializedName(SERIALIZED_NAME_SELF)
  @javax.annotation.Nullable
  private SdtmClassRef self;

  public static final String SERIALIZED_NAME_PARENT_PRODUCT = "parentProduct";
  @SerializedName(SERIALIZED_NAME_PARENT_PRODUCT)
  @javax.annotation.Nullable
  private SdtmProductRef parentProduct;

  public static final String SERIALIZED_NAME_PARENT_CLASS = "parentClass";
  @SerializedName(SERIALIZED_NAME_PARENT_CLASS)
  @javax.annotation.Nullable
  private SdtmClassRef parentClass;

  public static final String SERIALIZED_NAME_SUBCLASSES = "subclasses";
  @SerializedName(SERIALIZED_NAME_SUBCLASSES)
  @javax.annotation.Nullable
  private List<SdtmClassRefSubclass> subclasses = new ArrayList<>();

  public static final String SERIALIZED_NAME_PRIOR_VERSION = "priorVersion";
  @SerializedName(SERIALIZED_NAME_PRIOR_VERSION)
  @javax.annotation.Nullable
  private SdtmClassRef priorVersion;

  public SdtmClassLinks() {
  }

  public SdtmClassLinks self(@javax.annotation.Nullable SdtmClassRef self) {
    this.self = self;
    return this;
  }

  /**
   * Get self
   * @return self
   */
  @javax.annotation.Nullable
  public SdtmClassRef getSelf() {
    return self;
  }

  public void setSelf(@javax.annotation.Nullable SdtmClassRef self) {
    this.self = self;
  }


  public SdtmClassLinks parentProduct(@javax.annotation.Nullable SdtmProductRef parentProduct) {
    this.parentProduct = parentProduct;
    return this;
  }

  /**
   * Get parentProduct
   * @return parentProduct
   */
  @javax.annotation.Nullable
  public SdtmProductRef getParentProduct() {
    return parentProduct;
  }

  public void setParentProduct(@javax.annotation.Nullable SdtmProductRef parentProduct) {
    this.parentProduct = parentProduct;
  }


  public SdtmClassLinks parentClass(@javax.annotation.Nullable SdtmClassRef parentClass) {
    this.parentClass = parentClass;
    return this;
  }

  /**
   * Get parentClass
   * @return parentClass
   */
  @javax.annotation.Nullable
  public SdtmClassRef getParentClass() {
    return parentClass;
  }

  public void setParentClass(@javax.annotation.Nullable SdtmClassRef parentClass) {
    this.parentClass = parentClass;
  }


  public SdtmClassLinks subclasses(@javax.annotation.Nullable List<SdtmClassRefSubclass> subclasses) {
    this.subclasses = subclasses;
    return this;
  }

  public SdtmClassLinks addSubclassesItem(SdtmClassRefSubclass subclassesItem) {
    if (this.subclasses == null) {
      this.subclasses = new ArrayList<>();
    }
    this.subclasses.add(subclassesItem);
    return this;
  }

  /**
   * Get subclasses
   * @return subclasses
   */
  @javax.annotation.Nullable
  public List<SdtmClassRefSubclass> getSubclasses() {
    return subclasses;
  }

  public void setSubclasses(@javax.annotation.Nullable List<SdtmClassRefSubclass> subclasses) {
    this.subclasses = subclasses;
  }


  public SdtmClassLinks priorVersion(@javax.annotation.Nullable SdtmClassRef priorVersion) {
    this.priorVersion = priorVersion;
    return this;
  }

  /**
   * Get priorVersion
   * @return priorVersion
   */
  @javax.annotation.Nullable
  public SdtmClassRef getPriorVersion() {
    return priorVersion;
  }

  public void setPriorVersion(@javax.annotation.Nullable SdtmClassRef priorVersion) {
    this.priorVersion = priorVersion;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SdtmClassLinks sdtmClassLinks = (SdtmClassLinks) o;
    return Objects.equals(this.self, sdtmClassLinks.self) &&
        Objects.equals(this.parentProduct, sdtmClassLinks.parentProduct) &&
        Objects.equals(this.parentClass, sdtmClassLinks.parentClass) &&
        Objects.equals(this.subclasses, sdtmClassLinks.subclasses) &&
        Objects.equals(this.priorVersion, sdtmClassLinks.priorVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, parentProduct, parentClass, subclasses, priorVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SdtmClassLinks {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    parentProduct: ").append(toIndentedString(parentProduct)).append("\n");
    sb.append("    parentClass: ").append(toIndentedString(parentClass)).append("\n");
    sb.append("    subclasses: ").append(toIndentedString(subclasses)).append("\n");
    sb.append("    priorVersion: ").append(toIndentedString(priorVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("self", "parentProduct", "parentClass", "subclasses", "priorVersion"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SdtmClassLinks
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SdtmClassLinks.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SdtmClassLinks is not found in the empty JSON string", SdtmClassLinks.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SdtmClassLinks.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SdtmClassLinks` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `self`
      if (jsonObj.get("self") != null && !jsonObj.get("self").isJsonNull()) {
        SdtmClassRef.validateJsonElement(jsonObj.get("self"));
      }
      // validate the optional field `parentProduct`
      if (jsonObj.get("parentProduct") != null && !jsonObj.get("parentProduct").isJsonNull()) {
        SdtmProductRef.validateJsonElement(jsonObj.get("parentProduct"));
      }
      // validate the optional field `parentClass`
      if (jsonObj.get("parentClass") != null && !jsonObj.get("parentClass").isJsonNull()) {
        SdtmClassRef.validateJsonElement(jsonObj.get("parentClass"));
      }
      if (jsonObj.get("subclasses") != null && !jsonObj.get("subclasses").isJsonNull()) {
        JsonArray jsonArraysubclasses = jsonObj.getAsJsonArray("subclasses");
        if (jsonArraysubclasses != null) {
          // ensure the json data is an array
          if (!jsonObj.get("subclasses").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `subclasses` to be an array in the JSON string but got `%s`", jsonObj.get("subclasses").toString()));
          }

          // validate the optional field `subclasses` (array)
          for (int i = 0; i < jsonArraysubclasses.size(); i++) {
            SdtmClassRefSubclass.validateJsonElement(jsonArraysubclasses.get(i));
          };
        }
      }
      // validate the optional field `priorVersion`
      if (jsonObj.get("priorVersion") != null && !jsonObj.get("priorVersion").isJsonNull()) {
        SdtmClassRef.validateJsonElement(jsonObj.get("priorVersion"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SdtmClassLinks.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SdtmClassLinks' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SdtmClassLinks> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SdtmClassLinks.class));

       return (TypeAdapter<T>) new TypeAdapter<SdtmClassLinks>() {
           @Override
           public void write(JsonWriter out, SdtmClassLinks value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SdtmClassLinks read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SdtmClassLinks given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SdtmClassLinks
   * @throws IOException if the JSON string is invalid with respect to SdtmClassLinks
   */
  public static SdtmClassLinks fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SdtmClassLinks.class);
  }

  /**
   * Convert an instance of SdtmClassLinks to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

