// tslint:disable
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CtPackageCodelistsLinks,
    CtPackageCodelistsLinksFromJSON,
    CtPackageCodelistsLinksToJSON,
} from './';

/**
 * 
 * @export
 * @interface CtPackageCodelists
 */
export interface CtPackageCodelists  {
    /**
     * 
     * @type {string}
     * @memberof CtPackageCodelists
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CtPackageCodelists
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof CtPackageCodelists
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CtPackageCodelists
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof CtPackageCodelists
     */
    effectiveDate?: string;
    /**
     * 
     * @type {string}
     * @memberof CtPackageCodelists
     */
    registrationStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof CtPackageCodelists
     */
    version?: string;
    /**
     * 
     * @type {CtPackageCodelistsLinks}
     * @memberof CtPackageCodelists
     */
    links?: CtPackageCodelistsLinks;
}

export function CtPackageCodelistsFromJSON(json: any): CtPackageCodelists {
    return {
        'name': !exists(json, 'name') ? undefined : json['name'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'source': !exists(json, 'source') ? undefined : json['source'],
        'effectiveDate': !exists(json, 'effectiveDate') ? undefined : json['effectiveDate'],
        'registrationStatus': !exists(json, 'registrationStatus') ? undefined : json['registrationStatus'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'links': !exists(json, '_links') ? undefined : CtPackageCodelistsLinksFromJSON(json['_links']),
    };
}

export function CtPackageCodelistsToJSON(value?: CtPackageCodelists): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'label': value.label,
        'description': value.description,
        'source': value.source,
        'effectiveDate': value.effectiveDate,
        'registrationStatus': value.registrationStatus,
        'version': value.version,
        '_links': CtPackageCodelistsLinksToJSON(value.links),
    };
}


