/*
 * CDISC Library API
 *
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DefaultSearchResponseHitsInner {
    #[serde(rename = "href")]
    pub href: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl DefaultSearchResponseHitsInner {
    pub fn new(href: String, r#type: String) -> DefaultSearchResponseHitsInner {
        DefaultSearchResponseHitsInner {
            href,
            r#type,
        }
    }
}

