// tslint:disable
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RootSdtmClassVariableRef
 */
export interface RootSdtmClassVariableRef  {
    /**
     * 
     * @type {string}
     * @memberof RootSdtmClassVariableRef
     */
    href?: string;
    /**
     * 
     * @type {string}
     * @memberof RootSdtmClassVariableRef
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof RootSdtmClassVariableRef
     */
    type?: string;
}

export function RootSdtmClassVariableRefFromJSON(json: any): RootSdtmClassVariableRef {
    return {
        'href': !exists(json, 'href') ? undefined : json['href'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function RootSdtmClassVariableRefToJSON(value?: RootSdtmClassVariableRef): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'href': value.href,
        'title': value.title,
        'type': value.type,
    };
}


