/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CdiscLibraryApi);
  }
}(this, function(expect, CdiscLibraryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CdiscLibraryApi.XmlSendigClassDatasets();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('XmlSendigClassDatasets', function() {
    it('should create an instance of XmlSendigClassDatasets', function() {
      // uncomment below and update the code to test XmlSendigClassDatasets
      //var instance = new CdiscLibraryApi.XmlSendigClassDatasets();
      //expect(instance).to.be.a(CdiscLibraryApi.XmlSendigClassDatasets);
    });

    it('should have the property self (base name: "self")', function() {
      // uncomment below and update the code to test the property self
      //var instance = new CdiscLibraryApi.XmlSendigClassDatasets();
      //expect(instance).to.be();
    });

  });

}));
