/*
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.RootSdtmClassVariableLinks;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class RootSdtmClassVariable {
  
  @SerializedName("_links")
  private RootSdtmClassVariableLinks links = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public RootSdtmClassVariableLinks getLinks() {
    return links;
  }
  public void setLinks(RootSdtmClassVariableLinks links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootSdtmClassVariable rootSdtmClassVariable = (RootSdtmClassVariable) o;
    return (this.links == null ? rootSdtmClassVariable.links == null : this.links.equals(rootSdtmClassVariable.links));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.links == null ? 0: this.links.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootSdtmClassVariable {\n");
    
    sb.append("  links: ").append(links).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
