/*
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.QrsItem;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class XmlQrsItem {
  
  @SerializedName("self")
  private QrsItem self = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public QrsItem getSelf() {
    return self;
  }
  public void setSelf(QrsItem self) {
    this.self = self;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XmlQrsItem xmlQrsItem = (XmlQrsItem) o;
    return (this.self == null ? xmlQrsItem.self == null : this.self.equals(xmlQrsItem.self));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.self == null ? 0: this.self.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class XmlQrsItem {\n");
    
    sb.append("  self: ").append(self).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
