// tslint:disable
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AdamDatastructureLinks,
    AdamVarset,
} from './';

/**
 * @export
 * @interface AdamDatastructure
 */
export interface AdamDatastructure {
    /**
     * @type {string}
     * @memberof AdamDatastructure
     */
    ordinal?: string;
    /**
     * @type {string}
     * @memberof AdamDatastructure
     */
    name?: string;
    /**
     * @type {string}
     * @memberof AdamDatastructure
     */
    label?: string;
    /**
     * @type {string}
     * @memberof AdamDatastructure
     */
    description?: string;
    /**
     * @type {string}
     * @memberof AdamDatastructure
     */
    _class?: string;
    /**
     * @type {AdamDatastructureLinks}
     * @memberof AdamDatastructure
     */
    _links?: AdamDatastructureLinks;
    /**
     * @type {Array<AdamVarset>}
     * @memberof AdamDatastructure
     */
    analysisVariableSets?: Array<AdamVarset>;
}
