// tslint:disable
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ExportCdashigDomainVariablesRow,
    ExportCdashigScenarioVariablesRow,
} from './';

/**
 * @export
 * @interface ExportCdashigTable
 */
export interface ExportCdashigTable {
    /**
     * @type {Array<ExportCdashigDomainVariablesRow>}
     * @memberof ExportCdashigTable
     */
    domain_variables?: Array<ExportCdashigDomainVariablesRow>;
    /**
     * @type {Array<ExportCdashigScenarioVariablesRow>}
     * @memberof ExportCdashigTable
     */
    scenario_variables?: Array<ExportCdashigScenarioVariablesRow>;
}
