// tslint:disable
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    QrsResponsegroupRefElement,
    QrsResponsegroupsRef,
} from './';

/**
 * @export
 * @interface QrsResponsegroupsLinks
 */
export interface QrsResponsegroupsLinks {
    /**
     * @type {QrsResponsegroupsRef}
     * @memberof QrsResponsegroupsLinks
     */
    self?: QrsResponsegroupsRef;
    /**
     * @type {Array<QrsResponsegroupRefElement>}
     * @memberof QrsResponsegroupsLinks
     */
    responsegroups?: Array<QrsResponsegroupRefElement>;
}
