/* tslint:disable */
/* eslint-disable */
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QrsResponsegroupRef
 */
export interface QrsResponsegroupRef {
    /**
     * 
     * @type {string}
     * @memberof QrsResponsegroupRef
     */
    href?: string;
    /**
     * 
     * @type {string}
     * @memberof QrsResponsegroupRef
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof QrsResponsegroupRef
     */
    type?: string;
}

/**
 * Check if a given object implements the QrsResponsegroupRef interface.
 */
export function instanceOfQrsResponsegroupRef(value: object): value is QrsResponsegroupRef {
    return true;
}

export function QrsResponsegroupRefFromJSON(json: any): QrsResponsegroupRef {
    return QrsResponsegroupRefFromJSONTyped(json, false);
}

export function QrsResponsegroupRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): QrsResponsegroupRef {
    if (json == null) {
        return json;
    }
    return {
        
        'href': json['href'] == null ? undefined : json['href'],
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function QrsResponsegroupRefToJSON(json: any): QrsResponsegroupRef {
    return QrsResponsegroupRefToJSONTyped(json, false);
}

export function QrsResponsegroupRefToJSONTyped(value?: QrsResponsegroupRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'href': value['href'],
        'title': value['title'],
        'type': value['type'],
    };
}

