/* tslint:disable */
/* eslint-disable */
/**
 * CDISC Library API
 * REST API Documentation for CDISC Library in production server
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: cdisc_library_support@cdisc.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RootCdashigDomainFieldRef } from './RootCdashigDomainFieldRef';
import {
    RootCdashigDomainFieldRefFromJSON,
    RootCdashigDomainFieldRefFromJSONTyped,
    RootCdashigDomainFieldRefToJSON,
    RootCdashigDomainFieldRefToJSONTyped,
} from './RootCdashigDomainFieldRef';
import type { CdashigDomainFieldRefVersion } from './CdashigDomainFieldRefVersion';
import {
    CdashigDomainFieldRefVersionFromJSON,
    CdashigDomainFieldRefVersionFromJSONTyped,
    CdashigDomainFieldRefVersionToJSON,
    CdashigDomainFieldRefVersionToJSONTyped,
} from './CdashigDomainFieldRefVersion';

/**
 * 
 * @export
 * @interface RootCdashigDomainFieldLinks
 */
export interface RootCdashigDomainFieldLinks {
    /**
     * 
     * @type {RootCdashigDomainFieldRef}
     * @memberof RootCdashigDomainFieldLinks
     */
    self?: RootCdashigDomainFieldRef;
    /**
     * 
     * @type {Array<CdashigDomainFieldRefVersion>}
     * @memberof RootCdashigDomainFieldLinks
     */
    versions?: Array<CdashigDomainFieldRefVersion>;
}

/**
 * Check if a given object implements the RootCdashigDomainFieldLinks interface.
 */
export function instanceOfRootCdashigDomainFieldLinks(value: object): value is RootCdashigDomainFieldLinks {
    return true;
}

export function RootCdashigDomainFieldLinksFromJSON(json: any): RootCdashigDomainFieldLinks {
    return RootCdashigDomainFieldLinksFromJSONTyped(json, false);
}

export function RootCdashigDomainFieldLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): RootCdashigDomainFieldLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'self': json['self'] == null ? undefined : RootCdashigDomainFieldRefFromJSON(json['self']),
        'versions': json['versions'] == null ? undefined : ((json['versions'] as Array<any>).map(CdashigDomainFieldRefVersionFromJSON)),
    };
}

export function RootCdashigDomainFieldLinksToJSON(json: any): RootCdashigDomainFieldLinks {
    return RootCdashigDomainFieldLinksToJSONTyped(json, false);
}

export function RootCdashigDomainFieldLinksToJSONTyped(value?: RootCdashigDomainFieldLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'self': RootCdashigDomainFieldRefToJSON(value['self']),
        'versions': value['versions'] == null ? undefined : ((value['versions'] as Array<any>).map(CdashigDomainFieldRefVersionToJSON)),
    };
}

