extends Resource
class_name SdtmigDatasetVariable

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# SdtmigDatasetVariable Model


# Required: False
# Example: 42
# isArray: false
@export var ordinal: String = "":
	set(value):
		__ordinal__was__set = true
		ordinal = value
var __ordinal__was__set := false

# Required: False
# Example: LBDTC
# isArray: false
@export var name: String = "":
	set(value):
		__name__was__set = true
		name = value
var __name__was__set := false

# Required: False
# Example: Date/Time of Specimen Collection
# isArray: false
@export var some_label: String = "":
	set(value):
		__some_label__was__set = true
		some_label = value
var __some_label__was__set := false

# Required: False
# Example: Date/time of specimen collection represented in ISO 8601 character format.
# isArray: false
@export var description: String = "":
	set(value):
		__description__was__set = true
		description = value
var __description__was__set := false

# Required: False
# Example: Timing
# isArray: false
@export var role: String = "":
	set(value):
		__role__was__set = true
		role = value
var __role__was__set := false

# Required: False
# Example: Char
# isArray: false
@export var simpleDatatype: String = "":
	set(value):
		__simpleDatatype__was__set = true
		simpleDatatype = value
var __simpleDatatype__was__set := false

# Required: False
# Example: Exp
# isArray: false
@export var core: String = "":
	set(value):
		__core__was__set = true
		core = value
var __core__was__set := false

# Required: False
# Example: ISO 8601
# isArray: false
@export var describedValueDomain: String = "":
	set(value):
		__describedValueDomain__was__set = true
		describedValueDomain = value
var __describedValueDomain__was__set := false

# Required: False
# Example: TODO
# isArray: true
@export var valueList: Array:
	set(value):
		__valueList__was__set = true
		valueList = value
var __valueList__was__set := false

# Required: False
# isArray: false
@export var Underscorelinks: SdtmigDatasetVariableLinks:
	set(value):
		__Underscorelinks__was__set = true
		Underscorelinks = value
var __Underscorelinks__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__ordinal__was__set:
		bzz_dictionary["ordinal"] = self.ordinal
	if self.__name__was__set:
		bzz_dictionary["name"] = self.name
	if self.__some_label__was__set:
		bzz_dictionary["some_label"] = self.some_label
	if self.__description__was__set:
		bzz_dictionary["description"] = self.description
	if self.__role__was__set:
		bzz_dictionary["role"] = self.role
	if self.__simpleDatatype__was__set:
		bzz_dictionary["simpleDatatype"] = self.simpleDatatype
	if self.__core__was__set:
		bzz_dictionary["core"] = self.core
	if self.__describedValueDomain__was__set:
		bzz_dictionary["describedValueDomain"] = self.describedValueDomain
	if self.__valueList__was__set:
		bzz_dictionary["valueList"] = self.valueList
	if self.__Underscorelinks__was__set:
		bzz_dictionary["Underscorelinks"] = self.Underscorelinks
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("ordinal"):
		me.ordinal = from_dict["ordinal"]
	if from_dict.has("name"):
		me.name = from_dict["name"]
	if from_dict.has("some_label"):
		me.some_label = from_dict["some_label"]
	if from_dict.has("description"):
		me.description = from_dict["description"]
	if from_dict.has("role"):
		me.role = from_dict["role"]
	if from_dict.has("simpleDatatype"):
		me.simpleDatatype = from_dict["simpleDatatype"]
	if from_dict.has("core"):
		me.core = from_dict["core"]
	if from_dict.has("describedValueDomain"):
		me.describedValueDomain = from_dict["describedValueDomain"]
	if from_dict.has("valueList"):
		me.valueList = from_dict["valueList"]
	if from_dict.has("Underscorelinks"):
		me.Underscorelinks = SdtmigDatasetVariableLinks.bzz_denormalize_single(from_dict["Underscorelinks"])
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

